### ISSUE TITLE
关键岗位契约

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#104]
1. 关键岗位人员包括：教师，校长，项目负责人。
1. 老的产品服务模型下，让团队更高效，实现利润增长。
1. 教师和非教师比例从5:5调整到7:3。
1. 考虑与个人五年规划 #105、行业的机会点 #106 的衔接。
1. 兼顾无锡方面的诉讼。

**Comment by lidan1980** [comment]
1、关键岗位契约止步于公司章程的层面。这也是多次止步的地点。
2、划分资金池，及调动资金池里现金的先后次序来作为分配的来源。
3、不同岗位的人从不同的资金池里按照先后次序进行分配。
4、在企业章程里保证了第2点和第3点。
5、按照获客成本，课时单价和单节课时费毛利衡量非教师岗位的工作产出
6、以触达关键问题并行动签署开始真正的5年规划。
