### ISSUE TITLE
五年规划

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#105]
1. 结合关键岗位契约 #104的实际工作一起规划。
1. 参考 标准模型：通用个人模型 #101 定义：原始陷阱中行为、脱离原始陷阱的标志行为。
    - 标志行为首次出现：进入五年规划
    - 标志行为消失：规划中止
    - 标志行为重新出现：由受托者评估、修订规划。

**Comment by lidan1980** [comment]
1、首先克服“小农”意识开始。发布公式：今天我们讨论的问题，公布的方案，由于我自己过往工作的缺陷，我们虽然签署了，为了在接下来的执行中更高效的推进，有可能在10天之内会修正，在修正期内，你希望以怎样的方式对我可能产生的自私行为，自保行为进行约束，也请你提前说给我。如果过了这个自我察觉期限，对方可以根据你提出的方案内容询问依据，你必须以  外部法律 or 案例统计 两种方式之一恢复，否则就是无依据的提议
2、信息过载。节点非常明确到了难点和关键点就会出现过载现象。
