### ISSUE TITLE
一级规划

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#109]
1. 可以提前半年准备权利分配规则。
1. 可以协调研究、开发部门。
1. 可以管理行业头部企业--能力乘以3~5倍。

**Comment by lidan1980** [comment]
三个关键点管理、算法、二者结合。

1、管理：
问题：欺上瞒下，结党营私，相互倾轧，缺陷保护，双输。
情景：经历几乎每个团队都会存在。
目标：脱手运行，效率倍增
方案：
A、负面行为清单列表，犯错处罚。---错误认定机制，认定后处罚不受干扰机制。
B、目标动态调整机制。---每季度与责任人检视目标，并作出调整（触达下限调人）。
C、分级决策。
D、利益共享。

**Comment by hyg** [comment]
- 提前半年：就是2021年3月份要使用。
- 规则：就是财务用来算出各人利益、包括负数；员工用来判定指令的合法性；法院用来判决、强制执行。

该拿出规则的，输出感悟和原则就是辞职。

**Comment by lidan1980** [comment]
1、基础IT技术的学习，有能力为构建权力和利益分配的规则匹配一个平台。
2、通用工单的使用，阻止下滑的工作模型。
3、试错型共同体构建，跟踪3次行业头部的技术迭代。
