### ISSUE TITLE
二级规划

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#110]
1. 捕捉短期时间窗口，快进快出。
1. 一次性权利分配，规则老化前兑现退出。

**Comment by lidan1980** [comment]
具体的一次性分配方案：
关于成立决策委员会的方案
最近六个月内关键事项决策的方案
1、重要人事决定，校长以上人事任免薪酬制度调整由人事委员共同决定。
2、重要投资行为，校区或项目开设，超过10万元以上的一次性投资，由投资委员会共同决定。
3、组织关键决策，校区关闭，组织结构调整，企业并购事项，由管理委员会共同决定。
委员会由股东（至少1名）、经营负责人（1名）、部门主管及校长（5:1的比例选出）、员工代表（70:1的比例选出）组成。
1和2项由经营负责人召集会；3项由股东召集会议。
表决：一人一票，60%赞成可通过。事后评估，按照正确率计算权重。
任期：6个月。正确率排名，淘汰最后两名。空出名额重选。（每个议题的决策及概率，及接受全体员工质询，并入档案，跟随终身。每次竞聘每次述职都会出来。）

借用公司法。经理提出经营计划预算案。中间实际工作记录和决算按。经过程序进行修改，不能随便改。

赞成票和反对票都要有依据。

**Comment by hyg** [comment]
> 
> 
> 具体的一次性分配方案：
> 关于成立决策委员会的方案
> 最近六个月内关键事项决策的方案
> 1、重要人事决定，校长以上人事任免薪酬制度调整由人事委员共同决定。
> 2、重要投资行为，校区或项目开设，超过10万元以上的一次性投资，由投资委员会共同决定。
> 3、组织关键决策，校区关闭，组织结构调整，企业并购事项，由管理委员会共同决定。
> 委员会由股东（至少1名）、经营负责人（1名）、部门主管及校长（5:1的比例选出）、员工代表（70:1的比例选出）组成。
> 1和2项由经营负责人召集会；3项由股东召集会议。
> 表决：一人一票，60%赞成可通过。事后评估，按照正确率计算权重。
> 任期：6个月。正确率排名，淘汰最后两名。空出名额重选。（每个议题的决策及概率，及接受全体员工质询，并入档案，跟随终身。每次竞聘每次述职都会出来。）
> 
> 借用公司法。经理提出经营计划预算案。中间实际工作记录和决算按。经过程序进行修改，不能随便改。
> 
> 赞成票和反对票都要有依据。

1. 可以和公司法兼容（+职工代表大会）。
2. 经营负责人的候选人，以经营计划+预算案提出竞聘。以实际经营记录+决算案述职和回应新候选人挑战。
3. 淘汰结合通用工单、通用日志机制更加完善。
4. 加上修订程序（比如股东会和职工代表大会都80%以上通过），加上你个人领域确实持续地提交修订案，就成为一级规划。

注意准备对方的问题和回应素材，包括以问题形式提出的反对。

**Comment by lidan1980** [comment]
1、复习psmd关于公司法下治理结构的相关内容
2、解决一年内的组织重构的问题
3、关于决策机制的应用方面，可以容忍一部分实践中的天花板，用1-2个原始共同体进行训练。
