### ISSUE TITLE
接触与刺激

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#112]
1. 厘清各相关人在各规划中的选择（以行动而不是语言）。
1. 引入新人补齐空档，调整各人距离和契约。
1. 保持接触，适当施压，在互动中动态调整自己。

**Comment by lidan1980** [comment]
1、围绕混合式学习模型，算法支持下的教育方案输出重新构建自己的朋友圈。
2、对算法支持下的制度流程运行做出尝试。
