### ISSUE TITLE
主题B：职工参与机制

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#12]

**Comment by donaldshenfw** [comment]
职工参与机制

选定目标：
1. 案例：调研华为、阿里巴巴、复星、联想4家公司的职工参与机制案例，由沈文博主持；
2. 规律：每个人从4家公司的案例中，总结出1-5条共性规律，以及1-3条差异，由沈文博主持；
3. 方法学：根据学习中发现的共性和差异规律，挑选至少3条通过金瓯股东投票，达成蓝象职工参与机制的共识，一人一票，简单多数原则，请黄勇刚主持；

交流规则：
1. 工作环节由总结人分配任务，各成员分工负责资料搜集、整理。
2. 讨论环节“自由讨论”，随意发言，总结人认为有必要时要求、停止某成员发言。
3. 投票环节一人一票，简单多数通过，但仅作为职工参与机制筹备调研的股东方面意见素材，并不形成真正的股东会决议。

需要时间：
案例 60分钟，规律 90分钟，方法学 90分钟。

**Comment by donaldshenfw** [comment]
成果递延。
