### ISSUE TITLE
工单模式

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#120]
以权利固化的紧凑团队，完成外围业务工单化改造。
整理成员、劳动合同、劳务或承揽合同三方的特点，设计成员规章。

**Comment by hyg** [comment]
## 2021.6.22. 14:30:00 ~ 14:59:59
自有团队：
- 创始人：保底一切无人任务
- 接单、推广。
- 业务分析：
- 研发：
- 客服
- 后勤采购

服务商：
- 站长
- 骑手（司机）

**Comment by hyg** [comment]
## 2021.6.22. 20:00:00 ~ 20:59:59

- 创始人兼任接单推广或者业务分析之一，重点管理另一个工种。研发、客服、后勤采购相对容易管理。
- 网约车和外卖基本都是无人车运输的预备阶段，它们调试完毕后等待自动驾驶系统法人化，然后扩张。
- 教育培训行业没有无人车这个因素，但是教学模式不断变化，产生另一种核心能力 -- 模仿抄袭。
- 行业模仿中心的地位稳固之后，可以考虑行业金融中心的定位。

**Comment by hyg** [comment]
## 2021.6.22. 20:00:00 ~ 20:59:59

- 创始人兼任接单推广或者业务分析之一，重点管理另一个工种。研发、客服、后勤采购相对容易管理。
- 网约车和外卖基本都是无人车运输的预备阶段，它们调试完毕后等待自动驾驶系统法人化，然后扩张。
- 教育培训行业没有无人车这个因素，但是教学模式不断变化，产生另一种核心能力 -- 模仿抄袭。
- 行业模仿中心的地位稳固之后，可以考虑行业金融中心的定位。

**Comment by lidan1980** [comment]
- 中国的市场是分层，世界的市场也是分层的。给复制模式一个广阔的空间。
- 教培市场的需求是多元和分散的。相对更依赖人的经验。模式的成功也会具备多样性。
- 小米模式就是复制模式。手机复制评估，吹风机复制戴森，剃须刀复制飞利浦。
- 根据产品分类，根据人群分类，每一个交叉点上都有一种模型。
- 人才的平移和模式的平移一致，人才的复制和模式的复制一致。
- 为模式提供一体化方案，从生到死全过程。

**Comment by hyg** [comment]
## 小结

- 如果业务分析要产出书面文档，包括大量合同条款，委托者还需要一段时间实践锻炼才能胜任。
- 如果业务分析由职工负责，委托者和他可能会争夺决策权甚至企业实际控制权。自有团队的规章还需要时间设计、磨合。

**Comment by lidan1980** [comment]
- 外围的人不按照口头指令行动。必须按照工单，合同，承揽合同等穿透到执行层。不用客服，运营，站长去做。
- 教学点比外卖的站点又会复杂一些。无人车比机器取代教师更简单。
- 不要创新，外围甩出去，不能在业务上试错。在劳动关系上试错已经可以了。
- 有业务分析能力的人是权力的争夺者。
- 书面规则的输出要3-5年。
