### ISSUE TITLE
洗牌团队

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#122]
分析家长、公立学校、监管部门和民营机构的需求，预判行业洗牌阶段的生态位和团队配置。

**Comment by lidan1980** [comment]
1、	监管机构伴随“民意”（很多时候*民意*决定*上意*；上意决定监管机构的推进力度和执行手段）左右波动。教培企业涉及的利益链条短而且浅，所以在决策上的阻力较小。行业比较分散，执行标准难以统一或者量化。监管机构会在相对可以统一硬件基础，参与人员结构及任职资格，价格及资金等方面设计门槛。教育行业整体看，公立教育依然是主体，增加对公立教育体系的投入，提升其效率是必然选择。财政会投入。但是会花钱及敢花钱，会成为监管部门头痛的问题。性价比高，执行难度低，民生反应及公立体系内反应较好的模式会受到欢迎。打通学生学习数据，是监管机构未来有可能做得重要贡献。如果不做，则会由企业来做。
2、	公立学校即使在一个城市内，都是由强烈的分层的。拉平生源结构，师资结构都需要是时间。争夺资源的能力是公立学校的主要能力。能够帮助公立学校获得好的学生和老师的能力很值钱。
3、	家长大概率上会被新的分层方式所左右。或者积极寻找更新的分层方式，以便让自己和社会给自己的更好的定位。这些标准必须是显而易见的，可以量化的。如果不能量化，这个群体就会彷徨。所以综合测评，学校里的综合得分，同样会大量消耗家长和孩子的时间。这个时间的消耗相对于在游戏和其他不受管束的行为来看，性价比一直会是比较高的。直到现行的学制和课程标准改变。
4、	机构端，整个辅导形态发生改变。从实际意义上的主导者，变成参与者。新东方和学而思更像是一次农民起义军领袖。在一个灾荒的年代崛起后迅速衰亡，或者被收编或者自我革新。在这个阶段，辅助政府制定标准，辅助公校构建资源，辅助家长做好评价及定位，引导孩子更快更高效的在更短的时间内把学制内容学完，用派单式组织结构，提升现有教育资源（包括模式）利用价值。

**Comment by lidan1980** [comment]
以上是洗牌阶段各方情况的基本判断
