### ISSUE TITLE
松散联盟

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#123]
按照研究部门、核心机构、冒进机构各自独立，实际控制人不同、企业制度不同的情况，设计它们之间的契约，推演竞合关系的走向。

**Comment by hyg** [comment]
## 2021.6.23. 09:15:00 ~ 09:59:59

主播和平台的契约：
1. 新主播坚持4小时每天，两周直播。
2. 平台根据数据分析，提供流量支持。

流量起来后，运营员工来谈条件：
1. 免费给流量，挽留优质主播。
2. 付费签约，不能去其它平台，直接给钱主播。

字节跳动和旗下教育品牌的主要契约内容:
1. 旗下教育品牌可能低价拿到抖音流量。
2. 旗下教育品牌只能在抖音发。

字节跳动搞饱和攻击，每个业态赛马产生最强壮团队。
但目的是流量快速变现，没有深耕行业的耐心。

**Comment by hyg** [comment]
## 2021.6.23. 14:30:00 ~ 14:59:59

时间片用于讨论 高端职业教育：
- 就业市场→大学→中小学的压力传递。
- 一些属于大学的高端职业，客观上有童子功需求，可能产生专业特色的k12教育（包括全日制学校和校外辅导）。
- 特色课程的设计团队与一线精英频繁交流，在高考课程标准以外独立设计。
- 培训机构负责人应该以企业家视角，而不是消费者代表视角去做事。职责是保障就业市场的压力准确传递，不要失真，自己不要代入。

**Comment by hyg** [comment]
## 2021.6.23. 20:00:00 ~ 20:59:59

- 多寻找几家组成松散联盟；
- 竞合对象：
      - 选择教育行业作为变现途径的企业；
      - 教育培训行业大企业；
- 持续谈判：
      - 冒进机构试错成功后，并入对方；
      - 冒进机构试错受挫，对方根据情况续命或协助清算；
      - 个别的横向合作。

## 小结

这种模式下，委托者可以只关注短期热点，而且可以尽情施展 -- 可以省略核心部门、也没有实权上级。因此不需要纠正工作习惯。

**Comment by lidan1980** [comment]
- 从发现机会，到快速变现，到复制推广，在尽量短的时间内形成闭环。

- 技术、人才（经验）、资金等三个资源要素；学科，素质/素养，职业等三个领域；人与人，人与机器，机器与机器等三种业务形态。在这个范围内，尽量多发现机会。

- 组织形态类似教育培训的行业试错机会把握。
