### ISSUE TITLE
个人缺陷

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#124]
分析委托者自身缺陷，设计有效而安全的补救措施。接受实践检验。

**Comment by lidan1980** [comment]
1、	自然人mc。
2、	升一级的自然人mca。这个账户有1万元人民币。当出现{架空讨论，未明确上下级而讨论下一级任免问题，未明确修订权，讨论下级规章问题}情况。Mca账号当即注销。账户现金由参与讨论者裁决扣除现金额度，封顶1万，如果有剩余，归还自然人mc。（此规定自动写入合作协议。当mc以mca的账户出现时当即生效）

**Comment by lidan1980** [comment]
1、	自然人mc。
2、	升一级的自然人mca。这个账户有1万元人民币。当出现{架空讨论，未明确上下级而讨论下一级任免问题，未明确修订权，讨论下级规章问题}情况。Mca账号当即注销。账户现金由参与讨论者裁决扣除现金额度，封顶1万，如果有剩余，归还自然人mc。（此规定自动写入合作协议。当mc以mca的账户出现时当即生效）

**Comment by lidan1980** [comment]
充分理解以分身的模式去管理个人领域。作为升级的通路。
需要对自身缺陷进行复习分类。逐步分出若干账户。
构建一系列的个人与组织，个人与个人，分身与分身的协议。

**Comment by lidan1980** [comment]
对账号内容进行修订如下：

1、 自然人mc。
2、 升一级的自然人mca。这个账户有1万元人民币。当出现架空讨论，违反ps3，ps4标准（严格执行任免程序。上级人员未赴任（或被实质架空）时，不提名、不讨论下级人员。严格执行制定、修订程序。上级规章未生效（或被实质架空）时，不提交、不讨论下级规章。}情况。Mca账号当即注销。账户现金由参与讨论者裁决扣除现金额度，封顶1万，如果有剩余，归还自然人mc。（此规定自动写入合作协议。当mc以mca的账户出现时当即生效）

**Comment by lidan1980** [comment]
小结：针对于个人缺陷设计的容器在未来试错过程中有很大作用。具体操作还不熟练。思维精度和对于改变的畏惧，阻碍了账号的形成。但是没有强行交差，继续进行系统的学习，认真研究共同体难产，ps停滞，泛泛而谈，架空讨论，隐瞒和过滤等行为，形成新的分身。

**Comment by lidan1980** [comment]
小结：针对于个人缺陷设计的容器在未来试错过程中有很大作用。具体操作还不熟练。思维精度和对于改变的畏惧，阻碍了账号的形成。但是没有强行交差，继续进行系统的学习，认真研究共同体难产，ps停滞，泛泛而谈，架空讨论，隐瞒和过滤等行为，形成新的账户。
