### ISSUE TITLE
主题D：投融资业务流程、建模和竞争分析

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#14]

**Comment by zhangaizhi** [comment]
讨论规则：
1、我介绍10分钟，分解并提出问题；
2、Bill主要讨论第1、2问题，文博补充；20分钟
3、Donald主要讨论第3、4问题，Bill补充；20分钟
4、依托竞争分析，得出各项方法论。
需要60分钟；
1、tl专业平台（IT、激励、品牌）；
2、授权体系（业务、财人）；
3、公海与私海内部竞争策略
4、竞争分析（swot）

**Comment by zhangaizhi** [comment]
IT的推进：
1）由易到难、上传周报；
2）桃李的系统独立化、使用；
3）桃李IT系统有规划，尤其金瓯IT要有系统规划；
4）董事会专题会；

**Comment by zhangaizhi** [comment]
品牌的推进：
1）定位行业品牌，精品；
2）金瓯是什么，直接金融和间接金融；
3）FA=匹配能力（可IT、AI化）+服务能力（依赖于人）；
     理顺工作流、定价、授权【AI替代】；

**Comment by zhangaizhi** [comment]
投融资行业：底层行业云、资源、IT；
互联网金融 到 教育科技；
人才激励与发展；


##期末方程模型

<a name="roles" id="roles"></a >
###角色清单
1. 部署者
2. 投资方
3. 融资方
4. 员工

<a name="assets" id="assets"></a >
###资产清单
1. 资金
2. 其它资产
 1. 联合权益
3. 信息资产
 1. 参数组A1
  - 成员编号
  - 工种
  - 等级 
 2. 参数组A2
  - 成员编号
  - 资金
  - 联合权益
 3. 参数组A3
  - 工作参数名称
  - 工作参数定义
  - 工作参数采集要求
 4. 参数组A4
  - 成员编号
  - 工作参数
 5. 参数组A5
  - 联合权益：资金兑换比率（退权）
  - 联合权益：资金分配比率（分配）
  - 资金：联合权益兑换比率（增量上限以内行权）
  - 资金：联合权益兑换比率（增量上限以外行权）

 6. 方程组F1
  - 输入：
   - 工种
   - 等级
  - 输出：
   - 适用工作参数名称
 7. 方程组F2
  - 输入：
   - 工种
   - 等级
   - 工作参数
  - 输出：
   - 等级
   - 绩效评级
 8. 方程组F3
  - 输入：
   - 工种
   - 等级
   - 绩效评级
  - 输出：
   - 联合权益增量上限
 9. 方程组F4
  - 输入：
   - 工种
   - 等级
   - 绩效评级
  - 输出：
   - 报酬
 10. 契约C1
  - 劳动、劳务类契约的法定内容
  - 各参数组、方程组或其制定步骤，重点是参数组A1、A3，方程组F1、F4。
 11. 契约C2
  - 联合权益的行权、退权、分配规定
  - 参数组A5
  - 参数组A2变更内容

<a name="tasks" id="tasks"></a >
###任务清单
1. 初始化
2. 管理参数更新
3. 工作参数更新
4. 权益参数更新

<a name="coop" id="coop"></a >
###协作过程
1. 初始化
 1. 部署者根据模型部署利益共同体，确定以下事项：
  1. 明确本模型各部分采用何种方式实现。
  2. 选择采用企业或社团等方式的部分，按照法规办理设立手续。
  3. 选择采用合同实现的部分，编写合同模板。
  4. 选择采用软件实现的部分，编写软件并部署运行。
 2. 部署者选择权益办理者与财务。
 3. 完成一次管理参数更新。

2. 管理参数更新
 1. 部署者分析权益办理者的工作内容，确定其对应的A1、A3、F1、F4部分内容。
 2. 权益办理者分析财务、员工的工作内容，确定其对应的A1、A3、F1、F4部分内容。结合部署者的分析结果整理完整的A1、A3、F1、F4。
 3. 部署者批准A1、A3、F1、F4，或驳回由权益办理者根据批复意见修改直至批准。
 4. 权益办理者根据A1、A3、F1、F4内容，修订各员工的C1并安排签署生效。

3. 工作参数更新
 1. 权益办理者制定并更新F2，修改至部署者批准后生效。
 2. 员工根据A3收集工作数据提交给权益办理者，权益办理者结合A1、F1整理A4。
 3. 权益办理者根据A1、A4、F2，更新A1。

4. 权益参数更新
 1. 财务定期制定A5，修改至部署者批准后生效。
 2. 权益办理者定期制定并更新F3，修改至部署者批准后生效。
 3. 权益办理者根据A4、A5、F2、F3，起草各员工C2并与之协商调整，达成一致意见后安排签署。
 
<a name="alloc" id="alloc"></a >
###分配规则
1. 分配
 1. 权益办理者根据C1，计算各员工的报酬。财务根据报酬更新A2。
 2. 财务根据各员工实际签署的C2办理行权，更新A2。

2. 退权
 1. 员工根据C2条款提出退权，权益办理者检验是否符合C2条款。
 2. 如果符合C2，财务根据A5更新A2。

<a name="result" id="result"></a >
###实践结果
1. 华为虚拟受限股、华为TUP、联想联持会均符合这个模型。

<a name="statement" id="statement"></a >
###道德声明
1. 本文内容由作者根据公开信息整理而成，属于作者的工作成果。
2. 本文署名无争议。
3. 本文引用他人的公开成果已注明出处。
4. 本文未引用他人的未公开成果。
5. 一旦发现作者有违反此声明的行为，俱乐部有权视情节严重性给予公开惩罚。

**Comment by zhangaizhi** [comment]
1.建模此次完成不了；
2.机制和小组一级的合伙机制重合。
