### ISSUE TITLE
主题G：可信任的存储

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#17]
* 收集存储（或档案）的案例；
* 收集使用不同存储建立的共同体的案例；
* 分析存储可信度与共同体之间的规律。

其中，以**删改成本**定义存储的可信度。

由总结人分配时间并选择以下三种工作：

案例收集：由总结人提出要求，各成员把案例发到微信群中并讲解。
讨论表决：按照 http://blog.sina.com.cn/s/blog_591ac304010186yg.html 进行，由总结人根据贡献分配表决权。每个案例1\~2点，每个动议3\~5点。
集体推演：由总结人提出规则，各成员按规则参与推演。

**Comment by hyg** [comment]
收集案例：
* 提交：能够检验提交内容的合法性，拒绝非法的提交并在规定范围内警示；收到合法的新版本时可以自动提示旧版本调阅者。
* 调阅：能够检验调阅的合法性，拒绝非法的调阅并在规定范围内警示。

讨论表决，针对每个案例讨论：
* 是否符合提交和调阅要求。
* 可信度：非法修改、删除并产生效力的成本，必须提出具体操作步骤，作为成本分析的基础。

**Comment by zhangaizhi** [comment]
证监会审核IPO：
1、检验提供文件的合法合规性，拒绝非法提交并警示甚至惩罚；符合提交和调阅要求。
2、可信度较高

**Comment by hyg** [comment]
* 沈文博：2
部分可靠，上市公司公告@深交所、上交所官网 - 能够检验提交内容的合法性，拒绝非法的提交并在规定范围内警示；收到新版本不提示旧版本调阅者；拒绝非法调阅时不警示。

* 宁柏宇：3
部分可靠，工商备案 - 收到新版本不提示旧版本调阅者；拒绝非法调阅时不警示。
部分可靠，中国证券基金业从业协会 - 收到新版本不提示旧版本调阅者；拒绝非法调阅时不警示。

* 张爱志：2
证监会审核IPO：
1、检验提供文件的合法合规性，拒绝非法提交并警示甚至惩罚；符合提交和调阅要求。
2、可信度较高

下面是讨论表决：
宁柏宇提供的案例“工商备案 - 收到新版本不提示旧版本调阅者；拒绝非法调阅时不警示。”
其可信度有多高。

注册地址变更成本数量级为千元量级。 
1、伪造公司法定代表人签名和公章。 
2、伪造变更登记申请书。 
3、伪造公司委托代理人的委托书（提供代理人身份证）。 
4、伪造租赁协议书。 
5、提供新租地产权证。

**Comment by hyg** [comment]
下面是讨论文博提供的案例：
上市公司公告@深交所、上交所官网

其可信度有多高。

直接攻击深交所网站篡改某大型公司年报或重大投资事项，成本大概约数千万；收益来自于股价波动带来的投机机会，若市值在百亿，波动几个点会带来几亿收益。

**Comment by hyg** [comment]
下面是讨论案例：
按文件密级允许的最大范围分发副本，范围包括而不限于全体员工、消费者、竞争对手。
其可信度有多高。

可以同时提交这个方案的动议：
在报纸上刊登公告。其可信度有多高。

**Comment by hyg** [comment]
建立金瓯RIU，存储在：
按文件密级允许的最大范围分发副本，范围包括而不限于全体员工、消费者、竞争对手。
方案上，请分析一下RIU最大的发行量（以rmb计价）。

建立金瓯RIU，存储在：
按文件密级允许的最大范围分发副本，范围包括而不限于全体员工、消费者、竞争对手。
每个副本使用数字签名，包括金瓯和保存方的数字签名。
方案上，请分析一下RIU最大的发行量（以rmb计价）。

宁柏宇：
RIU的最大发行量取决于两个数值中的低值，其一是金瓯经济体所能承载的RIU，其二是可信赖存储RIU的数值存储上限。如采用按文件最大密级向员工、消费者、竞争对手发送，其上限是金瓯经济体所能承载的RIU数量级。目前教育行业全球年度金融交易总额为200-300亿人民币，金瓯收取交易费3%，大约5亿人民币，考虑到增发，应该在10亿人民币量级。 

如果金瓯体系能承载中国教育行业10%的交易，4万亿*10%=0.4万亿营收，放大至承载全球教育行业交易的10%，放大5倍约2万亿人民币。 

全球30亿电脑使用者，假设50%的人使用教育产品，10%使用金瓯的RIU，每人只使用1台电子设备，破解每台电子设备的成本是1万元，目前按文件最大密级发送的方案大约能承载1.5万亿。如果使用电子签名，破解每台电子设备的成本放大10倍至10万元，目前按文件最大密级发送文件和电子签名的方案大约能承载15万亿。 

所以金瓯RIU的最大发行量约为1万亿量级。

**Comment by hyg** [comment]
请列出建立在区块链及其派生技术的智能合约，及其研发者。

沈文博：Symbiont、R3CEV

**Comment by hyg** [comment]
存储（或档案）的案例：
* 上市公司公告@深交所、上交所官网
* 工商备案 
* 中国证券基金业从业协会
* 证监会审核IPO
* 按文件密级允许的最大范围分发副本，范围包括而不限于全体员工、消费者、竞争对手。
* 按文件密级允许的最大范围分发副本，范围包括而不限于全体员工、消费者、竞争对手。每个副本使用数字签名，包括金瓯和保存方的数字签名。

使用不同存储建立的共同体的案例：
* 在工商注册的企业
* （假设）基于副本分发发行RIU
* （假设）基于数字签名的副本分发发行RIU

存储可信度与共同体之间的规律：违规收益不超过存储可信度
