### ISSUE TITLE
主题H：母子公司的权利关系

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#18]

**Comment by ningboyu** [comment]
HYG的主题阐释：全世界范围内母子公司的权利关系？

主题目标：
总结全世界范围内母子公司的权利关系的方法学。

1、工作环节由总结人分配任务，各成员分工负责资料搜集、整理。
2、讨论环节采用正式讨论形式，采用IT合作社“在线议事规则” http://blog.sina.com.cn/s/blog_591ac304010186yg.html 在微信群中进行。
3、奖惩制度：累计投票制选出主题最佳贡献奖，可以投票给自己；所有参与讨论者（包括主持人）微信100元红包作为奖金池，最佳贡献奖得到所有奖金；如有平票，均分奖金。

需求2个时间段。
1、全世界范围内优秀母子公司的案例和规律？
工作时间1/3：写出你认为优秀的母子公司权利关系，阐述其3大特征。
讨论时间2/3：比较三个优秀的母子公司权利关系，阐述其共性。
2、全世界范围内优秀母子公司的共性规律？
工作时间1/3：写出蓝象母子公司现有的权利关系？
讨论时间2/3: 讨论蓝象母子公司应有的权利关系？

**Comment by ningboyu** [comment]
交流规则：

工作环节由总结人分配任务，各成员分工负责资料搜集、整理。
讨论环节有“自由讨论”和“正式讨论”两种模式，由总结人决定。
自由讨论随意发言，总结人认为有必要时要求、停止某成员发言。
正式讨论采用IT合作社“在线议事规则” http://blog.sina.com.cn/s/blog_591ac304010186yg.html 在微信群中进行。
以下权力、利益相关规则由总结人负责解释并登记。
权力的分配：在本次封闭交流期间，向所参与的共同体真实使用讨论结果方案而获得权力。
向所在共同体权力部门成员（其他股东、合伙人、社员）发出方案并征求意见的，以所在共同体内权力部门中表决权重作为本主题讨论中的权力。
向所在共同体权力部门成员（其他股东、合伙人、社员）发出方案作为正式动议的，以所在共同体内权力部门中表决权重的两倍作为本主题讨论中的权力。
没有明确章程的筹备期共同体，按照常用讨论群人员作为权力部门，按发起人三票、其他一人一票作为表决权。
参与多个共同体的，权力可以按上两条规则叠加。
权力的使用：在方案效果分析的正式讨论中，作为表决权重。
利益的分配：
所在共同体权力部门成员对征求意见做出正式反馈的，以反馈者在权力部门中表决权重累加入本主题讨论中的利益。
所在共同体权力部门成员对正式动议做出正式表决的，以表决者在权力部门中表决权重的两倍累加入本主题讨论中的利益。
利益的使用：
对外发出方案，每人次收入为一颗栗子。
每天结束时，按照投入的利益分配栗子。

**Comment by ningboyu** [comment]
hyg：
如果蓝象、桃李转移到金瓯的职权，不是基于客观规律和可验证的利益，而是无可无不可的选择。未来很难克服更高的沟通成本，很容易在蓝象、桃李内部又设置对应职能，或明或暗地把职权收回，架空金瓯。

**Comment by ningboyu** [comment]
关于建设金瓯共享后台的动议

（一）建设金瓯共享后台的目的
    金瓯设立的短期目的是为蓝象、桃李提供共享后台，包括人力、行政、财务、风控、信息系统等服务，提升服务效率，降低服务成本，打通底层数据；长期目的是成为智能化的教育行业服务平台，成长为业务单元。
    
（二）金瓯的股权结构
    金瓯目前的股东是自然人和公司法人，未来的股东会转为有限责任公司和有限合伙企业（或合作社企业），兼顾有历史贡献的老人和有突出能力的新人的利益。

（三）根据《公司法》，金瓯作为蓝象、桃李股东，行使下列股东会职权。
1. 决定公司的经营方针和投资计划；
2. 选举和更换非由职工代表担任的董事、监事，决定有关董事、监事的报酬事项；
3. 审议批准董事会的报告；
4. 审议批准监事会或者监事的报告；
5. 审议批准公司的年度财务预算方案、决算方案；
6. 审议批准公司的利润分配方案和弥补亏损方案；
7. 对公司增加或者减少注册资本作出决议；
8. 对发行公司债券作出决议；
9. 对公司合并、分立、解散、清算或者变更公司形式作出决议；
10. 修改公司章程；
11. 公司章程规定的其它职权。

（四）金瓯董事会聘任经理，对董事会负责，支持董事长工作。

（五）金瓯设置人力行政部、财务部、风控部、信息部，各部门负责人直线向金瓯董事长汇报，虚线向蓝象、桃李董事长汇报。

（六）金瓯授权蓝象、桃李董事长在人力、财务、风控、信息部具体业务的审批权，保留审核权。
