### ISSUE TITLE
控制人缺陷和治理效果

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#21]
主要讨论共同体实际控制人在知识结构、行使职权的勤勉、工作透明度、诚信度等等方面的缺陷。
* 案例：整理并定义各种影响治理效果的缺陷；
* 规律：分析各种缺陷之间主从关系；
* 规律：分析缺陷与治理效果的关系，主要是该缺陷下的治理效果极限；
* 方法学或工具：设计缺陷下的改进路径，也就是不改正该缺陷的前提下，怎么逐步提高治理效果直至达到极限。

**Comment by yinzhenya** [comment]
方法学

-适用范围：现有共同体实际控制人或股东在公司治理方面

规律及预期后果
   控制人认知能力、工作技能和低安全感等缺陷会导致工作透明度低，从而影响整个团队工作的透明度低，导致团队上下信任不足，决策质量下降，组织执行力弱。
    不使用本办法会使得公司失控的风险加大

具体内容：
   准备工作：
  -聘请律师团队对升级前共同体的法律关系进行梳理，整理问题改善清单
  -聘请会计团队对升级前共同体的财务账目进行审计，重点是重大财务投资、贡献计算和股东收益。

   实际控制人做出股权希释计划。面对社会和公司内部进行发标。对应企业不同的增长幅度。同时保证实际控制人单体股东最大。以有限合伙企业为持股平台的方式释放与增长幅度进行对应，20%释放，共同体规模和利润不低于5倍增长，40%释放，共同体规模和利润不低于10倍增长，60%释放，共同体规模和利润不低于50倍增长

 共同体非实际控制人的股权持有者为有限合伙企业（持股委员会）。持股委员会运行的规则严格按照《合伙企业法》运行，工作有行权记录，并保持可追溯机制。当共同体增速下降到约定百分比时候，持股委员会自动解散，由实际控制人召集新的持股委员会。

共同体按照约定分红享有权，共同体为此设立专用账号进行托管。内部托管的资金不得少于（）万元*2倍。

实际控制人的权力为：共同体的出售、并购、解散、融资等有一票否决权；

**Comment by bobinet** [comment]
希释计划->稀释计划

**Comment by bobinet** [comment]
共同体非实际控制人的股权持有者组建有限合伙企业（持股委员会）……
