### ISSUE TITLE
以股权引入人才

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#22]
中国公司法的有限责任公司以股权引入人才。
收集整理案例、规律和方法学，
并完成具体工具：针对每种方法学起草一套法律文件。

**Comment by bobinet** [comment]
所需讨论时间：60+60+60分钟

议事规则

1.每人至少介绍1个以股权引入人才的案例，提炼该案例的优点和缺点，后者提交案例的优缺点必须与前者不同（15分钟/人）
2.每人分别分析上节讨论案例的改进方法（15分钟/人）
3.针对总结人提出的问题，每人分别阐述如何在公司法框架内进行解决（15分钟/人）

**Comment by bobinet** [comment]
### 案例：
#### 共同体名称：A教育有限公司
1. 角色清单（具体岗位职责略）
	- 股东A、股东B、股东C、股东D
	- 执行董事：兼任总经理
	- 监事
	- 教师
	- 助教
	- 教学研究
	- 馆务管理员
	- 媒体宣传员
	- 行政人事 
2. 资产清单
	- 资金
	- 信息资产（学生数据、借阅记录、课程计划等）
	- 固定资产（电子设备、家具、图书等）
3. 任务清单
	- 招生
	- 教学
	- 课研
	- 学生服务
	- 信息系统建设
	- 决议执行（股东会）
	- 股东会议
	- 绩效考核（股东以外）
		- 根据每月的贡献值情况，计算绩效考核系数（骨干员工除了每月绩效考核之外，每半年计算半年考核系数）
	- 股东工作记录和绩效审查：
		- 制定每个股东的能力要求、阶段性承诺指标
		- 定期审查股东工作记录，重点排查与股东会决议的一致性、承诺兑现率、能力变化情况
		- 按照公式自动生成股东绩效考核系数
	- 人才引进
4. 协作过程
	- 股东会议
		- 收集动议
		- 集体讨论动议
		- 表决
5. 分配规则
	1. 按照签署的股东协议，明确各个股东认缴资金、方式和期限。股东A占40%，股东B占40%，股东C占15%，股东D占5%；认缴资金从股东协议签订之日起3年内完成认缴。
	2. 股东按照认缴资金比例享受对应股东会表决权
	3. 原有创始人将旧公司资产、资金转入本公司
	4. 所有股东必须完成当季度承诺80%，方可获得分红。当股东连续2个季度完成承诺低于80%，则该股东表决权降低50%，以此类推，直至表决权降为5%以下后按照退股方式处理。
	5. 每半年评估骨干员工的贡献值，获得半年分红。
	6. 利润分配规则：
		1. 每年进行一次利润分配
		2. 某方每年的所得分红=当年税后利润的70% × 某方分红系数 × 绩效考核系数
		3. 每年度绩效考核系数为当年度四个季度绩效考核系数的算术平均值。每季度绩效考核系数=本季度流失学生人数×0.3+本季度新增学生人数×0.2+（本季度课时总数-上季度课时总数）×0.5
		4. 分红系数：股东A 30%，股东B 30%，股东C 20%，股东D 10%，骨干员工奖励5%-10%
		5. 以上利润分配规则的调整由股东大会表决，须经代表三分之二以上表决权的股东通过，方可执行。

### 规律：
        1. 应单独编写“实践背景”一章，陈述清楚所总结的规律来自哪些实践工作。
        2. 每条规律应明确“鉴别标准”，提供检验是否符合该规律的标准。这些标准应易于理解、易于使用、无二义性。
        3. 每条规律应明确“预期后果”，陈述方式应清晰明确，易于鉴别该后果是否出现。
        4. 每条规律应至少提供两个实践案例。
        5. 根据以下因素评估其价值：
            * 现实中出现该规律的共同体的数量（或比率）。
            * 该规律的鉴别标准与预期后果的相关性。
1. 实践背景
	- A教育有限公司
	- NS北京公司 **
2. 规律内容：
	- 人才引进的审核程序不规范、审核人的奖惩和人才的奖惩不到位，必然难以引入有效人才，难以调动人才积极性。
	- 权力给予具备相应能力和提供承诺的人员。利益给予已有贡献者。共同体所有人员同工同酬。在此三个原则下，共同体将逐步实现公平竞争、优胜劣汰、良性发展的环境。三个原则不对应情况下，共同体将走向独裁、非实际控制人股东和员工积极性不高，甚至自留后路，损害共同体整体利益，努力谋取私利，进而脱离本共同体创业。
	- 绩效考核按照承诺和贡献值进行发放。股东、骨干人才等核心岗位的分红要递延发放。
3. 鉴别标准：
4. 预期后果：
4. 实践案例：
	- A教育有限公司
5. 价值评估   


### 方法学：
        1. 应单独编写“适用范围”一章，提供检验是否适用该方法的标准。这些标准应易于理解、易于使用、无二义性。
        2. 应单独编写“预期后果”一章，描述不运用该方法干预的后果。
        3. 应详细描述方法的内容，确保目标读者可以实施。如果该方法已经过实践验证，应整理实践案例。
        4. 应单独编写“成本分析”一章，明确运用该方法所需的人员、资金、设备、设施、社会关系、知识产权等资源。
        5. 应单独编写“效果分析”一章，陈述运用该方法的预期效果，实施该方法的效果扣除实施成本应明显优于不实施的后果，并进行分析论证。
        6. 根据以下因素评估其价值：
            * 现实中适用该方法的利益共同体的数量（或比率）。
            * 适用范围与预期后果的相关性。
            * 应用该方法与预期效果的相关性。
            * 实施效果扣除成本后优于不实施后果的程度。
1. 适用范围
2. 预期后果
3. 具体内容：
	- 人才引进：
		- 将共同体10%的股权作为标的，面向社会征求人才或者人才团队。引入人才按照10%股权认缴出资。
		- 按照现有利润额的20倍为公司估值，做为受让10%股权的货币价值核算依据。
		- 人才引入程序必须合规，如引入过程违反程序造成的代价，由引入人个人承担无限连带责任；
		- 人才引入的审核程序必须合规，组织现有股东会和董事会对申请的人才梯队进行审核。审核者要承担审核责任，未来该引入人才获益，审核者获得利益回报，否则审核者要出资补偿，不审核的股东或董事视为渎职，清除出股东会和董事会。
		- 引入人才按照承诺实现情况，兑现分红，分红为其承诺部分纯利润的30%。没有兑现承诺部分，由其自有资金补足。
		- 公司未按约定提供资源或人才招募时披露的公司内部信息不完整、不真实，公司赔付2倍的实缴资金给新引入的人才。
		- 引入外部人才和选拔内部人才同步进行，部分参照《SHM.1.md》。
	- 股东转型升级：
		- 明确股东职权，排查历史记录、多退少补（资金），确保所有股东和员工同工同酬、公平竞争、优胜劣汰。
	   	- 对资本性质股东明确投资回报率要求，计算所需业绩情况，给予分红，不给予权利。
	   	- 对技术性质股东，要规定技术入股的交易标的物、估价、交付验收程序、手续、时间，技术成果所有权或使用权要转入共同体，在股权和利益方面给予兑现。
	   	- 对资本加技术性质股东，按照出钱又出力的方式。按照出资进行股权分分配，出力部分要用工资和绩效作为补充 。
	   	- 没有行使股东职权能力的出资人、部门人员，强制引入更强的替代人，或者签署永久委托法律文件、放弃权力，或者股转债，或者转至专业人才打理的持股平台。
	- 利益分配：
		- 股东和骨干员工的绩效考核奖金为递延期薪酬。所有递延绩效视工作性质决定，从6个月到3年不等。递延部分奖金将按照国家的利率进行利息计算。
		- 监事对股东、董事违规没有发现，要进行利益惩罚，直至罢免职务。
3. 成本分析
4. 效果分析
5. 价值评估
6. 实践结果
	- 原有3个创始人成功转入A教育有限公司（甲、乙、丙方），引入新股东（丁方）加入本公司。
	- 容易形成大股东操控大局，难以调动小股东积极性，新股东谋取私利（同工同酬、开放竞争、提高透明度、决议明文可追溯）
	- 利润分配周期太短，容易出现股东或骨干员工“大小月问题”（延长利润分配周期，分阶段、延后兑现利润）
	- 没有设置新股东加入门槛（共享收益、共担风险）

### 工具
        1. 应单独编写“适用范围”一章，提供检验是否适用该工具的标准。这些标准应易于理解、易于使用、无二义性。
        2. 应明确“使用该工具的过程”，确保目标读者可以运用。如果该工具已经实践使用，应整理实践案例。
        3. 应单独编写“成本分析”一章，明确运用该工具所需的人员、资金、设备、设施、社会关系、知识产权等资源。
        4. 应单独编写“效果分析”一章，陈述运用该工具的预期效果，并进行分析论证。
        5. 根据以下因素评估其价值：
            * 现实中适用该工具的利益共同体的数量（或比率）。
            * 使用效果扣除成本后优于不使用后果的程度。
1. 适用范围
3. 使用过程
	- 股东会
		- 依据《公司法》第三十七条和本公司章程，审议《人才引入和奖励制度》
		- 依据《公司法》第三、四、二十三、二十五、二十七、二十八、三十七条和本公司章程，制定和审议《股东任职能力要求》、《股东承诺书》
		- 依据《公司法》第三十七条和本公司章程，审议《股东、董事会、监事会成员绩效考核方案》
	- 董事会
		- 依据《公司法》第四十六条和本公司章程，制定《人才引入和奖励制度》
		- 依据《公司法》第四十六、四十九条和本公司章程，制定和审议《经理以下人员绩效考核方案》
	- 监事会
		- 依据《公司法》第五十三条和本公司章程，定义检查公司账务，确保按照股东会和董事会决议执行。一旦违规，要求违规者纠正，否则召集临时股东会处置或提起诉讼。	
3. 成本分析
4. 效果分析
5. 价值评估
