### ISSUE TITLE
非股权引入人才

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#23]
以非公司方式，或公司下以不稀释股权的方式引入人才。
收集整理案例、规律和方法学，
并完成具体工具：针对每种方法学起草一套法律文件。

**Comment by lidan1980** [comment]
正文：
非股权引入人才模型
非股权引入人才是纳思基于治理和运营现状的重要方式。由于不涉及股权问题，所以人才引进具备时间段，效率高的特征。同时要规避权力机关的干预，尤其是涉及到人才薪酬获取的时间，周期，比例和金额的问题时。
本模型将利用《公司法》与《合同法》的具体条款对人才的引进所涉及到的契约关系进行合法化，固化。利用“保险基金”的办法，保障人才的利益。利用“稀缺定价法”吸引行业顶尖人才参与。
法律体系
根据《公司法》第（）条规定，当出现（）情况下，可以不经（）。授权给（）执行人才引入模型。
根据《合同法》第（）条规定，组织和个人签订民事合同。并到指定的公正处公正。当出现纠纷的时候依照《合同法》第（）条规定，具体裁定。
权益保障金
成立权益保障金。出资方式“公司49%，人才49%，人才直接管理者2%”。成立权益保障委员会。动议半数以上通过。保障金的总额>=人才年薪总额。
收益获取
1、完成当期目标，按照目标结果，由保障金直接划拨到个人账户。
2、未完成目标，按照要求，保障金直接将人才49%投入额划为公共资金。
3、期间只要获得时间节点信号及录入目标结果，形成自然判定，不需经过人力资源及其他任何部门及任何人，包括人才在内。资金自动划入。
4、权益获取范畴包括项目，校区，分公司及其他约定的可以获取的平台。
人才选用
1、选用方式：内部竞聘/猎聘/推荐；人才提出过往工作经历证明及对目标岗位的绩效承诺
2、选用成本：当年完成目标，选用人才的直接操作者将获得1/10年薪报酬；未完成指标或离职者，奖按照罚责，选用人才操作者讲作为第二偿还人，偿还“权益保障金”的亏损，偿还额度不高于1/20年薪报酬。
3、人才所有行权记录必须完全以书面形式进行。
突出贡献奖金
1、纳思不具备的能力，一年内，纳思没有第二个人或组织做到相同的指标水平；一年内，纳思没有人或组织提出同等水平和同样内容的提案。认定为突出贡献奖。
2、纳思奖以原有绩效奖金的基础上乘以2倍予以发放。
递延递增
1、所有薪酬绩效的30%为递延期薪酬。为了双向绑定员工承诺。
2、所有递延绩效视工作性质决定，从6个月到3年不等。
3、递延部分奖金将按照国家的利率进行利息计算。

**Comment by lidan1980** [comment]
# 非股权引入人才模型
非股权引入人才模型是共同体基于治理和运营现状最重要的人力组织方式。由于不涉及股权交易，所以人才引进具备时间短，效率高的特征。同时对涉及到人才薪酬获取的时间，周期，比例和金额予以保障。
本模型依照《公司法》与《合同法》的具体条款建立。
## 法律体系
根据《公司法》第四十六条规定，设置“高端人才事业部”，授权给事业部执行人启动非股权人才引入模型。
根据《合同法》分则第九章规定，组织和个人签订买卖合同。并到指定的公正处公正。
## 权益保障金
成立权益保障金。出资方式“公司占49%，人才占49%，人才直接管理者占2%”。高端人才事业部管理保障金。动议半数以上通过。保障金的总额>=人才年薪总额。
## 收益获取
1、完成当期目标，按照目标结果，由保障金直接划拨到个人账户。
2、未完成目标，按照要求，保障金直接将人才49%投入额划为公共资金。
3、期间只要获得时间节点信号及录入目标结果，形成自然判定，不需经过人力资源及其他任何部门及任何人，包括人才在内。资金自动划入。
4、权益获取范畴包括项目，校区，分公司及其他约定的可以获取的平台。
## 人才选用
1、选用方式：内部竞聘/猎聘/推荐；人才提出过往工作经历证明及对目标岗位的绩效承诺
2、选用成本：当年完成目标，选用人才的直接操作者将获得1/10年薪报酬；未完成指标或离职者，奖按照罚责，选用人才操作者讲作为第二偿还人，偿还“权益保障金”的亏损，偿还额度不高于1/20年薪报酬。
3、人才所有行权记录必须完全以书面形式进行。
## 突出贡献奖金
1、一个财务年度内，共同体内没有第二个人或组织做到相同的指标水平，认定为突出贡献奖。
2、共同体以原有绩效奖金的基础上乘以2倍予以发放。
## 递延递增
1、所有薪酬绩效的30%为递延期薪酬。为了双向绑定员工承诺。
2、所有递延绩效视工作性质决定，从6个月到3年不等。
3、递延部分奖金将按照国家的利率进行利息计算。

**Comment by bobinet** [comment]
#### 非股权引入人才模型
非股权引入人才是纳思基于治理和运营现状的重要方式。由于不涉及股权问题，所以人才引进具备时间段，效率高的特征。同时要规避权力机关的干预，尤其是涉及到人才薪酬获取的时间，周期，比例和金额的问题时。
本模型将利用《公司法》与《合同法》的具体条款对人才的引进所涉及到的契约关系进行合法化，固化。利用“保险基金”的办法，保障人才的利益。利用“稀缺定价法”吸引行业顶尖人才参与。

- 法律体系
   - 根据《公司法》第（）条规定，当出现（）情况下，可以不经（）。授权给（）执行人才引入模型。
   - 根据《合同法》第（）条规定，组织和个人签订民事合同。并到指定的公正处公正。当出现纠纷的时候依照《合同法》第（）条规定，具体裁定。

- 权益保障金
   - 依靠信托法，应用数字签名的方式，成立权益保障金，由第三方对资金进行监管，任何权益保障金的出资人不得操控本资金。出资方式“公司49%，人才49%，人才直接管理者2%”。成立权益保障委员会。动议半数以上通过。保障金的总额>=人才年薪总额。

- 收益获取
   - 完成当期目标，按照目标结果，由保障金直接划拨到个人账户。
   - 未完成目标，按照要求，直接将人才49%保障金投入额划为公共资金，并清零其保障金占比。
   - 期间只要获得时间节点信号及录入目标结果，形成自然判定，不需经过人力资源及其他任何部门及任何人，包括人才在内。资金自动划入。
   - 权益获取范畴包括项目，校区，分公司及其他约定的可以获取的平台。
   - 所有薪酬绩效的30%为递延期薪酬。为了双向绑定员工承诺。所有递延绩效视工作性质决定，从6个月到3年不等。递延部分奖金将按照国家的利率进行利息计算。

- 人才选用
   - 选用方式：内部竞聘/猎聘/推荐；人才提出过往工作经历证明及对目标岗位的绩效承诺
   - 选用成本：当年完成目标，选用人才的直接操作者将获得1/10年薪报酬；未完成指标或离职者，奖按照罚责，选用人才操作者讲作为第二偿还人，偿还“权益保障金”的亏损，偿还额度不高于1/20年薪报酬。
   - 人才所有行权记录必须完全以书面形式进行。
   - 公司未按约定提供资源或人才招募时披露的公司内部信息不完整、不真实，按照要求，直接将公司49%保障金投入额划为个人账户。

- 突出贡献奖金
   - 纳思不具备的能力，对于考核指标明确的岗位，一年内，纳思没有第二个人或组织做到相同的指标水平（指标要在引入人才前准备的提出）；对于考核指标难以明确的岗位：一年内，纳思没有人或组织提出同等水平和同样内容的提案。以上两者情况认定为突出贡献奖。
   - 纳思奖以原有绩效奖金的基础上乘以2倍予以发放。

**Comment by lidan1980** [comment]
因为是依赖《信托法》董事会、股东会、运营团队不能使用保障金，包括递延部分。
