### ISSUE TITLE
局部激励方案引入人才

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#24]
共同体的发展继续引入人才，但由于实际控制人的缺陷，共同体治理水平对人才缺乏吸引力。
在实际控制人不愿改进自身缺陷的前提下，按工具要求设计几套局部激励方案引入人才。
每套方案要明确以下几类人的责权利，并预判以下几类人的反应，基于他们的反应评估方案的综合治理效果：
* 有历史贡献、有既得利益，已退出管理工作；
* 有历史贡献、有既得利益，未退出管理工作；
    * 没有有能力承担未来工作，但不愿意退出；
    * 有能力承担未来工作，但不愿意接受监督考核；
* 没有历史贡献，有能力承担未来工作；

**Comment by lidan1980** [comment]
# 局部人才激励
## 角色清单
董事会（临时或局部）、内部员工、外部人才、人力资源、第三方调查机构、第三方托管机构
## 资产清单
企业资金、员工资金、人力资源薪酬模型、链式决策模型
## 任务清单
薪酬结构确定、发标书、薪酬调研、制定预算、设定触发点
## 协作过程
1/人力资源委托第三方调查机构出具行业薪酬报告
2/人力资源根据薪酬报告的数据制定出高于行业最高水准50%基准薪酬方案
3/董事会向公司内部和外部发出任务。任务涉及经营目标达成，新产品开发，管理模型开发等。
4/人力资源统计报名人数并公布报名人员的工作经历及可证明的工作成果
5/人力资源召集入围人员开会，会议现场竞标。目标达成所需时间最短，预算最低者获得职位。
6/董事会牵头成立“人才基金”基金由共同体49%+人才49%+人才直接管理者2%>=人才薪酬总额
7/按照出资比例召开第一届运营会议。在完成总目标的前提下确定保障人才胜任岗位的基础目标达成时间节点。由三方任意一方提案，表决每人一票。通过后，人才未完成，则人才直接管理者和人才同时失去项目管理权力。
8/一年内，共同体内没有第二个人或组织做到相同的指标水平；一年内，共同体没有人或组织提出同等水平和同样内容的提案。认定为突出贡献奖。纳思奖以原有绩效奖金的基础上乘以2倍予以发放。
9/未按规定承诺完成项目，则人才49%的资金划入地方托管的共同基金。
## 不完全实践结果
2017年3月份按照行业最高标准150%的薪酬标准引入人才，自主招聘8人，负责3家学习中心（一家换地址，一家新开业），进度顺利，组织中层管理培训4场。未做共同基金，未做突出贡献激励设置。
## 预期适应性
在公司有3类人员，就以上制度对3类人员进行编号，并预测其在模型执行的各界阶段的反映及最终结果进行推演。
1.1有历史贡献、有既得利益，已退出管理工作；
1.2有历史贡献、有既得利益，未退出管理工作； 
2.1没有有能力承担未来工作，但不愿意退出；
2.2有能力承担未来工作，但不愿意接受监督考核；
3没有历史贡献，有能力承担未来工作；
 
## 预期后果
各类员工之间容易形成分裂，支持者更公开。实施的话权力会快速集中并迅速优胜劣汰，没有人能保护缺陷，尤其是在中标到第一次运营会阶段开始加速分化。
## 成本分析
1/原有基础上人力成本增加50%，目标达成时间缩短50%或同等时间目标达成超额50%以上，则实际成本未增加。
2/淘汰了能力差的员工，减少了资源占用和浪费，提升了整体效率。
3/以上为推论需在项目推行1个完整的财务年度后方可获取验证数据。
4/新增第三方机构薪酬调研成本
5/新增第三方机构托管基金成本
6/调用《链式共同体》部分内容知识购买成本
7/4、5、6成本为可控成本，对最后成本结构不造成超过0.2%的影响。

**Comment by lidan1980** [comment]
![image](https://cloud.githubusercontent.com/assets/28098921/25493648/74df0d9a-2ba9-11e7-866c-32660d7139d8.png)
[](url)

**Comment by lidan1980** [comment]
## 预算保障
第一次运营会设定预算，预算金额从收入口直接划拨，其他人员无法干预。
董事会和人才及人才直接管理者开会通过会议表决可以更改预算。
如预算无法划拨，则当期目标直接归零，人才收益不受影响。
