### ISSUE TITLE
核心团队与共同体的交易

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#25]
整理权力、决策、监察、执行（主要是ceo、cfo、分支机构负责人）部门成员与共同体的交易案例，每项交易必须列出：
* 成员的角色；
* 交易的条件：时间？外部事件？指令？内部事件？...
* 具体标的物：成员把什么交付给共同体，共同体把什么交付给成员；
* 标的物交付、接收、使用的程序安排。

每个实际案例分别评价这些实际交易的合法性。
分析其规律，就常见问题设计出具体改进方案（工具）。

**Comment by yinzhenya** [comment]
基本规律：
 根据市场公允价格（实际的行业价格），   提高透明度，吸引优秀的人进入权力、决策、监察、执行部门，开放竞争，同工同酬。否则，会造成权力、决策、监察、执行部门与共同体的交易暗箱操作，导致决策、监察、执行质量下降。

方法：
权力部门成员（包括股东、合伙人、社员）与共同体的交易
交易的标的物
聘任董事、监事与考核及报酬的动议
经营方针、投资计划的动议
修改公司章程的动议
批准公司的使命、价值观、战略、基本目标与全员价值利益分配原则的动议
审议批准董事会的报告的动议
审议批准监事会的报告的动议
审议批准公司的年度财务预算方案、决算方案的动议
章程规定的其他动议

标的物交换的程序由股东大会明确。
每项标的物的交易价格由股东会确定（10000元---150000元），已经在运营的共同体，统计过去核心团队成员实际工作结果和报酬，分解出交易标的物,由股东会确定。
议事方式和表决程序按照《社员会议网络议事简易版》或《罗伯特议事规则简易版》执行。

决策部门成员（包括董事、合伙人等）与共同体的交易
-交易标的物
决定聘任解聘公司总经理、副总经理、财务负责人、分公司经理等高级管理人员极其考核的动议
决定公司的经营计划和投资方案的动议
制订公司的年度财务预算方案、决算方案的动议;
决定公司管理机构设置的动议
制定公司的基本管理制度的动议
制订人力资源基本政策的动议
其他公司章程要求的动议

董事按照固定年薪和每项动议的贡献值来由股东会确定收入。
标的物交换的程序由股东大会明确。
董事会分定期会议和临时会议，定期会议每一月、三月、五月、七月、九月、十一月 第一周周一上午召开     。如需调整，经由三分之二以上董事通过。临时会议由董事长召集 ，于召集会议前3日通知。
每项标的物的交易价格由股东会确定（10000元---150000元），批复公司章程之外工单2000元/份。
董事会决议已经在运营的共同体，统计过去核心团队成员实际工作结果和报酬，分解出交易标的物。
 如董事是股东，一次会议不提出动议，则判定为不作为。两次不作为，自动扣除其持有股份的5%，第三次不作为，自动扣除其持有股份10%，第四次，20%。
  如董事不是股东，则两次不作为，直接停发董事工资，三次不作为，取消董事资格。
  议事方式和表决程序按照《社员会议网络议事简易版》执行或《罗伯特议事规则简易版》执行

监察部门成员（包括监事、合伙人等》与共同体的交易
交易标的物
      检查公司财务的动议。
　　对董事、高级管理的工作记录进行查阅，人员执行公司职务的行为进行监督，对违反法律、行政法规、公司章程或者股东会决议的董事、高级管理人员提出罢免的建议的动议。
　　当董事、高级管理人员的行为损害公司的利益时，要求董事、高级管理人员予以纠正的动议。
　　提议召开临时股东会会议，在执行董事不履行《公司法》规定的召集和主持股东会会议职责时召集和主持股东会会议的动议
　　向股东会会议提出议案的动议。
　　对董事和高级管理层成员进行离任审计的动议。
      对本公司的经营决策、风险管理和内部控制等进行审计，并指导本公司内部审计部门的工作的动议。
      监事可以对决定事项提出质询或者建议的动议
       股东会授予的其他权利的动议。

   监事按照固定年薪和每项动议的贡献值来由股东会确定收入。
   标的物交换的程序由股东会明确。每项标的物的交易价格由股东会确定（10000元---150000元），已经在运营的共同 体，统计过去核心团队成员实际工作结果和报酬，分解出交易标的物，由股东会确定。
 - 如监事一次会议不提出动议，则判定为不作为。两次不作为，接停发监事工资，三次不作为，取消监事资格。
    议事方式和表决程序按照《社员会议网络议事简易版》执行或《罗伯特议事规则简易版》执行

　　执行部门（经理、分支机构负责人等）与共同体的交易
       交易标的物
      主持公司的日常经营管理工作，组织实施执行董事会的决定;
　　组织实施公司年度经营计划和投资方案;
　　拟订公司内部管理机构设置方案;
　　拟订公司的基本管理制度;
　　制定公司的具体规章;
　　决定聘任或者解聘除应由董事会决定聘任或者解聘以外的负责管理人员;
　　董事会授予的其他职权。

    执行层按照固定年薪和董事会制定的绩效考核来确定收入
   标的物交换的程序由董事会明确。每项标的物的交易价格由董事会确定（10000元--150000元），已经在运营的共同体，统计过去核心团队成员实际工作结果和报酬，分解出交易标的物，由股东会确定。
执行层对董事会负责，行使相关职权，不能执行相关动议，扣减工资直至取消经理资格。
 议事方式和表决程序按照《社员会议网络议事简易版》执行或《罗伯特议事规则简易版》

**Comment by bobinet** [comment]
- 规律;控制人会阻挠公开化，对量化的结果不能接受，不能根据市场公允价格（实际的行业价格），会阻挠优秀的的人进来，导致共同体衰弱。要开放竞争，同工同酬。

#### 权力部门成员（包括股东、合伙人、社员）与共同体的交易
- 交易标的物
聘任董事、监事与考核及报酬的动议
经营方针、投资计划的动议
修改公司章程的动议
批准公司的使命、价值观、战略、基本目标与全员价值利益分配原则的动议
审议批准董事会的报告的动议
审议批准监事会的报告的动议
审议批准公司的年度财务预算方案、决算方案的动议

- 标的物交换的程序由股东大会明确。
- 交易价格确定： 
每项标的物的交易价格由股东会确定（5000元以上，不设上限），已经在运营的共同体，统计过去核心团队成员实际工作结果和报酬，分解出交易标的物。
- 议事方式和表决程序按照《社员会议网络议事简易版》执行

#### 决策部门成员（包括董事、合伙人等）与共同体的交易
-交易标的物
1、决定聘任解聘公司总经理、副总经理、财务负责人、分公司经理等高级管理人员极其考核的动议
3、决定公司的经营计划和投资方案的动议
4、制订公司的年度财务预算方案、决算方案的动议;
5、决定公司管理机构设置的动议
6、制定公司的基本管理制度的动议
7、制订人力资源基本政策的动议
8、其他公司章程要求的动议

- 标的物交换的程序由董事会明确。
- 交易价格确定： 
董事按照固定年薪和每项动议的贡献值来确定收入
标的物交换的程序由股东大会明确。每项标的物的交易价格由股东会确定（5000元以上，不设上限），已经在运营的共同体，统计过去核心团队成员实际工作结果和报酬，分解出交易标的物。董事会提前给出决策事项，给充足的准备时间。
   - 如董事是股东，一次会议不提出动议，则判定为不作为。两次不作为，自动扣除其持有股份的5%，第三次不作为，自动扣除其持有股份10%，第四次，20%。
   - 如董事不是股东，则两次不作为，直接停发董事工资，三次不作为，取消董事资格。
- 议事方式和表决程序按照《社员会议网络议事简易版》执行

………………
