### ISSUE TITLE
部署升级前的个人准备

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#26]
当共同体模型和股份制度冲突时，共同体向更高形式部署。
设计方法学或工具：部署者个人在此之前需要完成哪些准备，积累什么样的历史记录。

其中历史记录的要求是：
* 部署方案的新内容，加上部署者过去行为的任何组合，都不能给其他方造成损失。
* 负面记录不能消除，只能用正面记录去稀释。同一事项的记录可以按整体比例使用。

**Comment by bobinet** [comment]
### 主题内容和要求
当共同体模型和股份制度冲突时，共同体向更高形式部署要求。设计方法学或工具：部署者个人在此之前需要完成哪些准备，积累什么样的历史记录。其中历史记录的要求是：

   - 部署方案的新内容，加上部署者过去行为的任何组合，都不能给其他方造成损失。
   - 负面记录不能消除，只能用正面记录去稀释。同一事项的记录可以按整体比例使用（客观、全面地对待以往的对
错，不得人工篡改）。

### 讨论过程
- Steve.Lin：
   - 冲突类型：
      - 改进现有控制人、股东的缺陷
      - 未兑现利益的保护机制和公司法冲突
      - 权力、利益无法分开
   -  准备工作：理清自己的3个记录+参与决议文件，
   -  历史记录：资产记录、贡献记录、能力记录、承诺记录、参与决议文件  
- 李：
    - 冲突类型：股东或合伙人的责任承担程度不一、权责不匹配
    - 准备工作：
        - 法律保障（确保股东不能中途要求暂停升级、暂停就退股），定期审核；
        - 今后个人决议明文可追溯
        - 理清共同体中利益相关方的信息（含亲戚）
        - 个人身体情况
    - 历史记录：财产记录、决策记录、承诺记录
- 尹：
    - Null
- 黄：
    - 冲突类型：权利、利益不可拆分；权利和股份可买卖、可继承
    - 准备工作：
        - 分析升级后实际控制人的控制权问题（假如实际控制人失去共同体控制权，必然不会支持此升级），以此判断升级空间；
        - 能力优者必然不断完善和展示自我能力记录，积累资本，吸引关注，为升级做准备
        - 兑现创始人和股东未兑现的利益
    - 历史记录：能力记录、承诺记录

### 总结
#### 方法学
- 适用范围：
	- 现有共同体模型与公司法在权利分离、未兑现利益保护、控制人或股东缺陷治理等方面存在冲突的案例
- 预期后果：
	- 不使用本方法会加大共同体模型升级的难度，降低升级成功率。
- 具体内容：
	- 准备工作：
		- 聘请律师团队对升级前共同体的法律关系进行梳理，整理问题改善清单
		- 聘请会计团队对升级前共同体的财务账目进行审计，重点是重大财务投资、贡献计算和股东收益。
		- 整理原有股东的工作记录、透明度（工作记录的完整性、准确性、流程、公开范围）、诚信度（工作记录与事前计划或约定对比）
		- 整理未兑现利益的数量和人员名单
		- 整理现有共同体的缺陷，包括但不限于“三会”组织缺陷、权力与利益获得途径及两者关系、利益兑现（含未兑现利益的保护机制）、激励机制等
		- 分析现有共同体实际控制人升级后权力和利益可能受到的影响
		- 分析新旧共同体模型对权力、决策、监察、执行部门等要求的区别
		- 分析升级后共同体对权力、决策、监察、执行部门人员的透明度、诚信度、能力要求
		- 明确升级后共同体的价值观、行为习惯、财务目标及组织目标，并组织相关人员培训
		- 结合升级后共同体的各种要求对现有员工进行压力测试
		- 整理新股东所需门槛（能力和承诺）和薪酬
		- 完善自己行为执行过程，做到准确、相对明文、可追溯
		- 判断自我身体的承受能力和时间要求（EGO）
		- 如果部署者（实际控制人）的准备工作检测次数超过预定次数并决定停止升级，部署者（实际控制人）应无条件同意其他共同体成员离职和退股（如其他共同体成员提出的），并给予经济补偿。
		- 如果部署者（实际控制人）的准备工作检测次数超过预定次数并决定停止升级，应授权原共同体的其他成员全权推动共同体的升级，原共同体部署者（实际控制人）可以用货币、实物、土地、知识产权等方式作为新共同体出资，但不具备权力，出资按照共同体的成员协议享受收益。
	- 所需积累的历史记录：
		- 现有共同体的资产清单（含自己）：资金、设备
		- 现有共同体的贡献记录（含自己）
		- 现有共同体的能力记录（含自己）
		- 现有共同体的承诺记录（含自己）：股东协议、项目计划、承诺书
		- 现有共同体的决议文件（包含收益和亏损的操作决议）
	- 准备工作检测：
		- 周期性检测部署者（实际控制人）以上准备工作的完成情况（以实际行动的历史记录为判定依据），完成所有准备工作则启动升级，否则暂缓升级，由部署者（实际控制人）继续准备。检测次数超过预定次数，停止升级。
		- 检测周期、检测次数由原共同体的权力部门确定
- 成本分析
	- 费用：内部和外部人员薪酬、外购服务费用
	- 人员：内部、外部人员（会计、律师、专家、医生等）
	- 财物：内部和外部相关资料
- 效果分析
	- 使用该方法完成共同体升级后，将破解现有共同体权利无法分离、未兑现利益难以保护、控制人或股东缺陷无法治理等问题。
	- 完成共同体升级后，将大大提高权利、决策、监事、执行部门人员的积极性，提高工作效率，提升共同体的整体利润。
- 价值评估

#### 工具
- 适用范围：
	- 现有共同体模型与公司法在权利分离、未兑现利益保护、控制人或股东缺陷治理等方面存在冲突的案例
- 使用过程：
1. 资产清单工具：
	- 股东会动议1：依据《公司法》第二十三条、第三十七条和本公司章程,委托--律师所在--年--月--日前对升级前共同体的法律关系进行梳理，提交架构图、权责清单等资料
	- 股东会动议2：依据《公司法》第二十三条、第三十七条和本公司章程，委托--会计所在--年--月--日前对升级前共同体的财务账目进行审计，提交注册会计师签名确认的审计报告。
	- 股东会动议3：依据《公司法》第三十七条和本公司章程，委托——-在--年--月--日前整理原有股东的工作记录，计算原有股东的透明度（工作记录的完整性、准确性、流程、公开范围）、诚信度（工作记录与事前计划或约定对比）
	- 股东会动议4：依据《公司法》第三十七条和本公司章程，委托——-在--年--月--日前整理现有共同体的缺陷，包括但不限于“三会”组织缺陷、权力与利益获得途径及两者关系、利益兑现（含未兑现利益的保护机制）、激励机制等
	- 股东会动议5：依据《公司法》第三十七条和本公司章程，委托——-在--年--月--日前整理现共同体的历史记录（资产清单、贡献记录、能力记录、承诺记录、决议文件），并将以上资料向新共同体的股东公开
2. 知识准备工具：
	- 股东会动议6：依据《公司法》第三十七条和本公司章程，委托——-在--年--月--日前分析新旧共同体模型对权力、决策、监察、执行部门等要求的区别
	- 股东会动议7：依据《公司法》第三十七条和本公司章程，委托——-在--年--月--日前整理新股东所需门槛（能力和承诺）和薪酬
	- 董事会动议1：依据《公司法》第四十六条和本公司章程，委托——-在--年--月--日前
		- 分析升级后共同体对权力、决策、监察、执行部门人员的透明度、诚信度、能力要求
		- 明确升级后共同体的价值观、行为习惯、财务目标及组织目标
		- 结合升级后共同体的各种要求对现有员工进行培训和压力测试
3. 心理干预工具：
	- 股东会动议8：依据《公司法》第三十七条和本公司章程，委托——-在--年--月--日前整理未兑现利益的数量和人员名单
	- 股东会动议9：依据《公司法》第三十七条和本公司章程，委托——-在--年--月--日前分析现有共同体实际控制人升级后权力和利益可能受到的影响
	- 股东会动议10：依据《公司法》第三十七条和本公司章程，行使如下工作：
		- 如果部署者（实际控制人）的准备工作检测次数超过预定次数并决定停止升级，部署者（实际控制人）应无条件同意其他共同体成员离职和退股（如其他共同体成员提出的），并给予经济补偿。
		- 如果部署者（实际控制人）的准备工作检测次数超过预定次数并决定停止升级，并由原共同体成员自行设立新共同体，原共同体部署者（实际控制人）可以用货币、实物、土地、知识产权等方式作为新共同体出资，但不具备权力，出资按照共同体的成员协议享受收益。
	- 制定个人学习计划和工作规则，完善自己行为执行过程，做到准确、相对明文、可追溯
	- 调用个人管理模型，判断自我身体的承受能力和时间要求
- 成本分析：
	- 费用：内部和外部人员薪酬、外购服务费用
	- 人员：内部、外部人员（会计、律师、专家、医生等）
	- 财物：内部和外部相关资料
- 效果分析：
	- 使用该工具完成共同体升级后，将破解现有共同体权利无法分离、未兑现利益难以保护、控制人或股东缺陷无法治理等问题。
	- 完成共同体升级后，将大大提高权利、决策、监事、执行部门人员的积极性，提高工作效率，提升共同体的整体利润。
- 价值评估：

### FYI
* 方法学：

        1. 应单独编写“适用范围”一章，提供检验是否适用该方法的标准。这些标准应易于理解、易于使用、无二义性。
        2. 应单独编写“预期后果”一章，描述不运用该方法干预的后果。
        3. 应详细描述方法的内容，确保目标读者可以实施。如果该方法已经过实践验证，应整理实践案例。
        4. 应单独编写“成本分析”一章，明确运用该方法所需的人员、资金、设备、设施、社会关系、知识产权等资源。
        5. 应单独编写“效果分析”一章，陈述运用该方法的预期效果，实施该方法的效果扣除实施成本应明显优于不实施的后果，并进行分析论证。
        6. 根据以下因素评估其价值：
            * 现实中适用该方法的利益共同体的数量（或比率）。
            * 适用范围与预期后果的相关性。
            * 应用该方法与预期效果的相关性。
            * 实施效果扣除成本后优于不实施后果的程度。
* 工具：

        1. 应单独编写“适用范围”一章，提供检验是否适用该工具的标准。这些标准应易于理解、易于使用、无二义性。
        2. 应明确“使用该工具的过程”，确保目标读者可以运用。如果该工具已经实践使用，应整理实践案例。
        3. 应单独编写“成本分析”一章，明确运用该工具所需的人员、资金、设备、设施、社会关系、知识产权等资源。
        4. 应单独编写“效果分析”一章，陈述运用该工具的预期效果，并进行分析论证。
        5. 根据以下因素评估其价值：
            * 现实中适用该工具的利益共同体的数量（或比率）。
            * 使用效果扣除成本后优于不使用后果的程度。
