### ISSUE TITLE
主题B：根据业务定制的财务制度

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#3]
## 25日总结：
1. 参考金融行业优秀标杆企业的财务制度，按照自身企业经营的实际需要，梳理设定对应的会计科目，建立匹配业务发展诉求的会计制度。
2. 从2016年第四季度开始，推进董事会层面讨论及确定由主管合伙人与财务人员递交的财务制度提案。通过一个季度至少一次的财务专项会议，持续迭代提升企业的财务管理水平。
3. 在2017年第一季度启动财务工作记录要求，明确列出财务相关的纸质表单、电子文件目录，细化填写要求、文件命名和保存方式。确保利用记录可以重建工作。管理纸质记录。

**Comment by donaldshenfw** [comment]
财务负责人根据外部政策法规、通知，内部规章、文件、投资规划和当前制度未能适用的工作记录（以下统称“启动文件”）制订、修订《财务管理制度》，并在启动文件发布30天内经过董事会批准正式发布。内容包括：
1. 会计核算规则：明确如会计科目、报表格式、各类收支项目等内容，以及各科目与各项收支的对应关系。
2. 税务规划：利用税法的规定，为企业税务支出的降低或减少而进行筹划。要求明确缴税金额与各项收支之间的数学关系，及其法律依据。
3. 工作记录要求：明确列出财务相关的纸质表单、电子文件目录，细化填写要求、文件命名和保存方式。确保利用记录可以重建工作。管理纸质记录。
4. 工作流程：明确财务相关工作的流程要求，文件应易于理解、易于操作、无二义性。
5. 数据交换需求：根据GB/T 24589-2010《会计核算软件数据接口》制定产品与财务软件的数据交换需求。

**Comment by cqhwang** [comment]
GB/T 24589-2010《会计核算软件数据接口》的更新版：GB/T 24589.1-2024 《财经信息技术 会计核算软件数据接口 第1部分：企业》

**Comment by hyg** [comment]
> GB/T 24589-2010《会计核算软件数据接口》的更新版：GB/T 24589.1-2024 《财经信息技术 会计核算软件数据接口 第1部分：企业》

这套标准目前生效的有：
[GB/T 19581-2004 信息技术 会计核算软件数据接口](https://openstd.samr.gov.cn/bzgk/std/newGbInfo?hcno=B52C6F0B88173267C694639C300D51B0)
[GB/T 24589.2-2010 财经信息技术 会计核算软件数据接口 第2部分：行政事业单位](https://openstd.samr.gov.cn/bzgk/std/newGbInfo?hcno=F28552BB9B784A66D23E606280C40972)
[GB/T 24589.4-2011 财经信息技术 会计核算软件数据接口 第4部分：商业银行](https://openstd.samr.gov.cn/bzgk/std/newGbInfo?hcno=C54D8F87DE41162A87BDA6E0B888E5A2)
[GB/T 24589.1-2024 财经信息技术 会计核算软件数据接口 第1部分：企业](https://openstd.samr.gov.cn/bzgk/std/newGbInfo?hcno=19CE9E504A6293ED573EF88D4ADF15B4)

但是会计核算软件企业自己搞了一套，比如用友：
- https://community.yonyou.com/index
	- https://www.yonyou.com/developer/developer/
	- https://community.yonyou.com/article/detail/10660
	- https://c2.yonyoucloud.com/iuap-hc-client/ucf-wh/client/index.html#/detail/LJQJCSSFFL1?nodeId=18c8e305-5cc6-43e7-b98e-4e3efe49fd6d&productline=CommunityDoc	
- 可以先按照BIP开发助手提出的几个数据结构开发分录记录（AER）、分录规则（分录模版AERT）。
	- 和SOP并列纳入修订链。
	- 业务打通之后，再拨出资源实现国标、金蝶的接口。数据内容应该相似。

更详细的手稿：https://codeberg.org/hyg/blog/src/branch/master/release/time/d.20260405.md#psmd-%E6%9D%83%E5%88%A9%E5%88%86%E9%85%8D%E8%AF%AD%E6%B3%95-engine
