### ISSUE TITLE
201705-1.cfm.case.3: register

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#30]
创始人D提出：“由D、F、G、H四人组成权力部门，决策权按照3:1:1:1分配，按1:1:1:1分红。大事要全体同意，一般事情半数通过。” F、G、H认可D的方案，确认准备全职加入。

D的助理准备了几套方案，都被工商局拒绝。由于各方不在一个城市，远程沟通很容易产生误解。D决定不再与其他三方商量，务必按照上次的共识创业。 请你为他设计几种不同方案，然后助理再去试试。

**Comment by ningboyu** [comment]
乙第1稿

关键是写出符合公司法和事前约定的公司章程。

1、公司注册时4人每人25%股份。
2、公司章程规定D拥有股东会1/2表决权，F、G、H各拥有1/6表决权。
依据：股东会会议按照出资比例行使表决权。公司章程另有规定除外。
3、公司章程规定4人为董事会成员。
4、公司章程规定D为董事长，H为经理。

**Comment by hyg** [comment]
甲第一稿:

成立一家有限责任公司，股东会、董事会由D、F、G、H组成，股权比例为D、F、G、H为13.33%，设置一个有限合伙企业，占有限责任公司股比为36.67%，GP为D，LP为D、F、G、H各25%，选举D为董事长、经理，股东会职权范围内的决策需全体同意通过，董事会职权范围内的决策需半数同意通过，董事会以下的事情，按照公司法标准章程授权的经理范畴行使职权。

**Comment by hyg** [comment]
201705-1.cfm.case.3：实施场景

企业注册的同时，开始整理过去几个月的工作记录。
发现经理职权基本由H履行，这些工作都需要即刻执行才能满足经营需要。
F对H的指令提出不少反对意见，D和G基本都需要半年以后才能判定对错。

请按交替方案一应对。

**Comment by hyg** [comment]
甲方案决策应对：

D发起召开董事会，任命H为经理，在股东会批准的战略和预算范围内行使职权；
半年后D发起召开股东会，根据F和H的历史决策正确与否，重新调整F和H的董事会投票权；
D发起召开董事会，根据H的历史表现，投票决定是否罢免其行使的经理职权；

**Comment by ningboyu** [comment]
交替方案一：
甲方案，乙监察，以F损害公司利益要求F停止干涉H的执行工作。
乙方案，乙决策，股东会决议，暂停F董事工作3个月。
丙方案，乙执行，H和F、G重新注册新公司，H、F、G个人占比为25%， 25%，25%；H、F、G组成有限合伙企业，占新公司25%股份，H是唯一GP，H、F、G各占有限合伙企业1/3。

**Comment by hyg** [comment]
乙方案执行应对：
H请F有不同意见时找监事，提出监督、纠正意见或者提请罢免；监事如果认为无异议，F可在董事会和股东会层面动议提出不同意见；

**Comment by hyg** [comment]
丙方案监察应对：
提议召开临时股东会会议，将D的各方面权力按照1:1:1暂时平分到F、G、H，直到D回来履行职责，重新召开股东会调整投票权和利益分配，冻结D在消失期间应得的分红权；
阶段性盘点所有历史上D、F、G、H在类似股东会、董事会、监事会和经理层面的职权贡献，评估未兑现利益，成立一个合伙企业，完成合法性授权移交，GP投票权一对一映射新注册的有限责任公司的股比，将这部分利益和新的股东承诺提交的利益，共同投入到新的有限责任公司里去；
提议聘请F、G、H都认可的第三方专家，对H的关键执行方案按季度或重要性进行评审，由公司支付相应的费用；
