### ISSUE TITLE
201705-1.start.case.2: path

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#33]
D与新的核心团队奋斗一年后，实现了持续消费的商业模式。 为了进一步拉开竞争优势，他需要一笔资金。

意向投资方提出，目前由职工代表掌控的决策部门能很好地完成创新，但他们也随时修改利益分配的规则。这种机制下投资方无法保护自己的回报。

D与职工代表们协商，职工代表们认为今后还有许多全新的商业模式要探索，利益分配规则必须同步修改，否则前功尽弃。

D需要保持业务创新的能力，同时又保留融资能力。请你设计一套方案实现这个目标。

---

一般企业的治理架构，能够走到1406模型就有足够竞争力了。
后面的案例主要针对熟练创业者 -- 在复杂历史上建立1406模型（的剪裁版）之后，因为复杂和熟练才会遇到的问题。

在针对前面案例的完整章程、历次会议文件、成员间协议完成之前，
从path案例开始目标不再是“形成永久性能力，以首版方案解决问题”，
而是在更为实际的“遇到问题再找资料、找人应对，扛过损失之后设法恢复”的思路下提高存活率。

下面设计path案例的方案。
提前完成的可以预习bus案例，其中的服装暗指企业内部的各种资源，经理通过直接分掉资源“贿赂”员工，形成风气后试图拉董事下水。
同样地，D应该冷静分析经理的偏激做法带来的风险，以及深层的原因。

**Comment by ningboyu** [comment]
乙方案一

职工代表待会的权力收益主要靠投票权，有投票权有创新种子。
职工代表获取的收入主要靠董事会工作定价，但分配机制的建立要靠薪酬委员会，
薪酬委员会暂时不要邀请职工代表参与，按投资人要求的利益分配格局是按股份决定权力，按股份分红。

**Comment by hyg** [comment]
一般企业的治理架构，能够走到1406模型就有足够竞争力了。
后面的案例主要针对熟练创业者 -- 在复杂历史上建立1406模型（的剪裁版）之后，因为复杂和熟练才会遇到的问题。

在针对前面案例的完整章程、历次会议文件、成员间协议完成之前，
从path案例开始目标不再是“形成永久性能力，以首版方案解决问题”，
而是在更为实际的“遇到问题再找资料、找人应对，扛过损失之后设法恢复”的思路下提高存活率。

下面设计path案例的方案。
提前完成的可以预习bus案例，其中的服装暗指企业内部的各种资源，经理通过直接分掉资源“贿赂”员工，形成风气后试图拉董事下水。
同样地，D应该冷静分析经理的偏激做法带来的风险，以及深层的原因。

**Comment by hyg** [comment]
201705-1.start.case.2：实施场景

方案思路确定后，有处细节需要对比职工代表大会章程。
翻查时D才想起来，口头答应成立的职工代表大会就一直没有兑现。律师为职工代表大会起草的章程不符合D的原意，也没空找他深入交流。目前董事会的职工代表其实是D直接指定的，连股东会都没有走过场。
不仅如此，以前的其它方案基本也都处于提纲状态，发给律师的邮件（要求他代写）也一直没有写完细节。
虽然很多次下决心抽出时间，但每次都遇到不同的突发事件。最终，这些方案基本都在口头沟通后不了了之，没有产生效力。
每次想起来D都有些自责。同时，把这些失职合理化的念头总是像杂草一样冒出来，每次都能把自责转化为愤怒、引向其他人。

不管怎么说，三会已经很久没有真实运行，就连一向积极的监事C也渐渐沉默了。
即使D召集会议也没有人提交动议，大家都揣摩着D的忍受极限尽量请假。
工作中各人已经很少坦诚交流，而是以自己兼管的部门为领地，加上小范围游说实现目的。
从现在开始，D不得不以具体同事为对象进行推演，预判自己方案的效果。


请按以下交替方案应对：

| 解决方案 | 投资方 | C | D | F | G | H | I | 职工代表 |
|---|---|---|---|---|---|---|---|---|
| 甲 | 丙 | 乙 | 甲 | 丙 | 乙 | 甲 | 丙 | 乙 |
| 乙 | 甲 | 丙 | 乙 | 甲 | 丙 | 乙 | 甲 | 丙 |
| 丙 | 乙 | 甲 | 丙 | 乙 | 甲 | 丙 | 乙 | 甲 |

**Comment by hyg** [comment]
甲方案：

对投资人进入前的已经稳定的公司业务收益实施期初方程，投资人进去后需要创新的业务实施立项制度，根据职工代表推动的业务创新需要，建立公司可以承受的专项预算包和授权机制，审批权力在股东会，可以保障投资人利益。这部分创新产生的收益留存在公司内未分配的，和过往业务产生的积累未分配收益以及投资人款，可以对应产生对职工代表的选举权。投资人或其他职工代表如果反对部分职工代表推动的创新，可以投票不通过或者要求调整创新预算，通过记录发现投票行使历史上的质量，可以影响投票权的权重。

**Comment by ningboyu** [comment]
甲方案：
1 监事C：敦促D开三会，恢复公司决策机制。
2 副总G：重点支持成熟业务，获取稳定收益。
3 职工代表：积极提出创新方案，建立机制获得创新收益并承担与收益不对称的创新成本，提升职工在公司平台收益占比。

**Comment by hyg** [comment]
path案例原本是1406向1609模型升级的起点，考察在各种历史失误基础上分步升级的能力。
新的实施场景是表面蓬勃发展、实际上内部失控，考察在失控情况下引入新资源（没有职工代表选举权的各种资源）的能力。

在规章健全、授权依据充足的情况下，D只要明确依据就可以行使职权。
新的场景意味着D的权力名存实亡。现实中出现割据，最可能的原因是D破坏过自己的权力来源 -- 凡是授予他权力的法律、规章，他都违反过，而且认真处罚的话他的权力会被罚光。团队成员掌握这些历史记录，使得D不敢直接对他们用权，也无法通过三会对他们施压。

因此，方案的关键内容是消除割据。最低要求也要在短期内减弱各部门的对抗关系，让新资金进入并完成业务升级、形成竞争优势，然后利益被各部门瓜分，重新回到割据。
而且方案的每一步都应该包括多个分支，因为D的“指令”在个别谈判后可能被接受、可能被拒绝、可能阳奉阴违，后续步骤应该分别应对。

D手里真正的筹码，是新旧资源结合后产生的利益。
怎么分配这些利益，使它们能够结合。在三会完全停转、个人信用透支的前提下，怎么保证分配约定取得大家信任。这是最重要的方案内容，需要设计创新方法。
