### ISSUE TITLE
201705-1.start.case.3: bus

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#34]
在一次董事会上，经理I给每位董事带来了一套高端服装，声称这是免费的工作服。

会后D到库房调研，得知全体员工都可以免费领取积压库存作为工作服。员工们觉得不领白不领，同时也抱怨库管员厚此薄彼，因为具体哪种产品积压由库管员说了算。销售人员则反映，经常因为缺货而失去到手的订单，却看到有员工从库房领到同型号的“积压”产品。 D问I是否了解这些情况，I表示也曾考虑过以现金形式发放工作服津贴，由员工自由购买。实行一段时间后发现产生的税负，一点不比之前的损失小，还不如让员工沾点便宜，至少有一部分积压真的消化掉了。 D对I的汇报将信将疑，又把库管员叫来质询。库管员表示I一直没有按预算拨付库房经费，他只好自己解决：找一些“有门路”的员工拿紧俏产品卖出去，货款都用在库房修缮上。作为回报，他在工作服发放时比较优待这些“地下销售”。

D看到了全员销售的机遇，但库管员这种方式过于粗放。他需要一套严密而又易于操作的机制，并且与原有的传统销售制度合二为一，而不是独立的两套制度。请你代他设计一下。

**Comment by ningboyu** [comment]
乙方案一

经理I和全体销售根据销量排名确定滞销产品，公司工服预算回购滞销产品做工作服。
库管员出库入库要有明确记录，经理I和董事长D签字，不能私自售卖产品做小金库。
销售售卖产品正常提成，非销售在完成本职工作前提下售卖出滞销产品正常提成，非销售人员不得售卖非滞销产品。

**Comment by ningboyu** [comment]
乙方案一（修订版）

1 D召集董事会通过库存和销售管理办法（简称“管理办法”），指派财务负责人。
2 管理办法通过预算建立IT系统统计财务、库存、销售数据，指派董事长挂帅监督IT系统建设，规定财务、库管员、销售负责人都有权查阅库存数据。
3 管理办法规定库管员出库入库要有书面记录，库管员汇总，财务审核和定期审计，如发现库管员私自售卖产品直接辞退。
4 管理办法规定销售负责人根据系统库存和销售记录情况确定滞销产品，经经理I和董事长D审核范围和数量，以公司工服预算成本价决定滞销产品品类和数量发放工作服，库管执行发放权，财务拥有审核权。剩余滞销产品成为全员销售产品，公示全公司。
5 管理办法规定财务负责人根据系统销售数据为销售和非销售人员提成，非销售在完成本职工作前提下售卖出滞销产品正常提成，非销售人员不得售卖非滞销产品。
6 董事会按季度审核决算情况，问责。

**Comment by hyg** [comment]
201705-1.start.case.3：实施场景

G已经成为全职成员，她对前瞻性问题的敏锐度不亚于D，逐渐成为业务创新的积极推动者。
但G常常在讨论中夹带不必要的对抗，模糊了D的方案重点，也使她的天份被工作琐事掩埋。

与其他各人的交流后，D意识到大家的实质关系已经倒退回parttime案例。
各人实际控制的部门和内部资源已成为个人私有，而且合法性不亚于D手中的权利。除非全票通过，否则即使形式上召开三会也无法执行决议。
相对于破除部门壁垒时的激烈反抗，大家对[销售收入]替代[工资、津贴]却意外地欢迎。

在三会彻底停转（尤其是预算、决算制度架空）的情况下，“全员销售”成了收回利益分配权、重新整合资源的机会。
回顾过去几年的经历，D决心直接迈入新阶段 -- 建立能在当下全票通过，经受过去六种案例而不失效的新模型。
为此他愿意赌上这次创业的全部权利。


请按以下交替方案应对：

| 解决方案 | 投资方 | C | D | F | G | H | I | 职工代表 |
|---|---|---|---|---|---|---|---|---|
| 甲 | 丙 | 乙 | 甲 | 丙 | 乙 | 甲 | 丙 | 乙 |
| 乙 | 甲 | 丙 | 乙 | 甲 | 丙 | 乙 | 甲 | 丙 |
| 丙 | 乙 | 甲 | 丙 | 乙 | 甲 | 丙 | 乙 | 甲 |
