### ISSUE TITLE
主题C： 早期专业共同体:成员以兼职、远程方式协作，能良好过渡到下一形态。

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#4]
## 25日总结：
1. 组织章程：参考优秀的DAC去中心化自治公司或去中心化自治社会的优秀案例，创建符合当前潜在的业务需求的共同体组织章程，确定其根本形态和协作方式，免去组织工商注册。
2. 成员合同：组织发起人或参与者写出参与该组织的成员合同，附带组织章程两份文件让全部成员签字确认，保障跨时空的高强度专业分工协作；
3. 客户合同：组织管理机构出具与业务客户商业委托相关的客户合同，组织销售职能部门确认与客户合同签署，保障远程紧密协作也能完成委托业务；
4. 未来计划：创建DAO去中心化的匿名网络协作组织，可以聚集更广的跨时空界限和专业分工的参与者，能够完成某主题（环境，农业）的社会化系统工程；

**Comment by Atomx3** [comment]
27日总结：
参考合作社法，“IT合作社章程”，十八条、工单管理条款；
参考公司法，第三十七条、第四十六条、第四十九条、第五十三条内容：按提交物计件计酬。

合作社创始社员早期贡献评估、补登记

十八、工单管理条款
工单承载每名社员的劳动，其劳动贡献值通过计量方法和工单类型计算。

（一）计量方法：
工单的数量和质量决定价值，价值决定其可兑现的法币价格，兑现比率为浮动非恒定，初始状态的工单价格为1JT/张，初始状态兑现为1元/JT；
某工单类型的价值计量，由合作社委员会表决决定；或者合作社委托第三方评估机构计量；

（二）工单类型：
工单类型描述的是工单承载的交易标的物的资产类型，根据XD合作社组织性质，设定类型如下：

货币资产：
以任何一种法币作为交易标的物；例如某社员为本社带来一笔1W元人民币的投资，则计算该张工单的可兑现贡献值为佣金1W*%；

非货币资产:
1. 实物；
2. 知识产权；
3. 空间使用权；
4. 劳务成果；
（接受哪些有限且已知的劳务成果清单？）

（三）工单记录
工单储存在XD合作社服务器中，保证其不可篡改，完整性和真实性，以及保障网络安全和不可攻击，所有社员都有权查询相关工单记录；

（四）工单生效
日程进度：每个任务生成的每张工单必须保障其日程进度的详情记录，根据完成进度计算贡献值；
验收标准：根据以上工单类型，检查日程进度、工单数量和完成度、及质量来计算贡献值；
预算费用：根据验收标准的结果支付预算费用；
兑现周期：参考本章程之“财务管理”，“分配制度”；
