### ISSUE TITLE
201705-1： 甲重新整理

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#42]
重修筹备、初创阶段，最少要完成以下内容：
* parttime：筹备协议
* lock：第一次筹备会议动议
* register：
    * 给助理的指令
    * 章程（或其它企业对应文件）
* opendoor：
    * 第三次筹备会议动议（筹备阶段结束）
    * 第一轮三会动议（根据需要制定，三会分开写）
    * 职工大会章程
    * 第一次职工大会动议（以下合并为“四会”）
* 1406：第二轮四会动议
* path：第三轮四会动议
* bus：第四轮四会动议
* token：第五轮四会动议

注意事项：
* 除了最少内容外，其它工作根据自己设想添加。所有书面、口头、暗示、合法、非法......的手段，一律作为方案的一部分整理、讨论。
* 如果前面步骤通过检查，后续步骤可以按照四会有效运转去制定。
* 甲写在这个专用issue下。

**Comment by donaldshenfw** [comment]
服装定制APP筹备协议
===========================================================
## 筹备协议
### 总则 
1. 团队成员D、E、F、G、H经协商决定于2017年07月05日成立筹备组，D作为筹备组召集人,E、F、G、H为筹备组成员。当筹备组成员不能按时完成工作时，D可以委任新的筹备组成员。
筹备组包含岗位如下：市场负责人、开发负责人、供应链负责人、运营负责人、筹备会议秘书；
       【D、E、F、G、H列出具体人名和身份证号和数字签名公钥字符串】
2. 有志于出任董事、监事、经理职务的筹备组成员，应在加入时声明。
       【D、E、F、G、H的声明】
3. 出现以下情况的成员退出筹备组：
       1. 筹备会议缺席或累计两次请假的；
       2. 筹备会议表决时不投票、投无效票的；
       3. 经主持人提醒后仍然违反议事规则的；
       4. 不执行筹备会议决议的；
       5.完成承诺的预期工作成果（工作成果通过向筹备会议秘书提交资产并获得签收回执得以确认），如果未能完成则取消资格，具体成果清单如下：
       5.1. 筹备召集人提交以下工作成果：
1. 经过筹备会议批准的共同体章程。
2. 主持第一届董事会、监事会选举。
3. 制定内部机构设置、管理制度、工资报酬标准。
4. 现有团队成员未签订正式合同的，制定合同并与安排补签。
5. 整理过往工作记录、单据、表单，财务数据，资产。
6. 补登工作结果（包括筹备工作），其中：
       1. 201x年m1月d1日及以前的工作按照m00%登记报酬；
       2. 201x年m1月d1日至筹备成功的工作按照n00%登记报酬。
       【根据筹备失败的风险估定比率，应高于团队成员平均预期，以便筹备期间强化工作纪律。】
7. 办理设立手续。

4. 第一届董事会、监事会选举产生后，筹备组向董事会移交以下材料并自动解散：
       1. 章程。
       2. 历次筹备会议记录、纪要。
       3. 已完成的内部机构设置、管理制度、工资报酬标准。
       4. 截止到解散时间的资金流量表及原始单据。
       5. 截止到解散时间的合同、协议及工作表单。
       6. 已在使用的各类账号、密码。
       7. 办理设立手续相关材料及结果证照。
5. 如果在201x年m2月d2日未能完成筹备工作，筹备组解散。筹备期间的工作成果由H咨询所有团队成员意见后，决定清算、分配方案并组织执行。

### 筹备工作
工作成果通过向筹备会议秘书提交资产，并获得签收回执，得以确认。
1. 制定章程，定于2017年8月5日提交筹备章程的草案，提交内容中能够被纳入章程讨论议程者，将有权力参加章程投票决策，具体由筹备召集人决定。章程通过后72小时内，将已创造的劳动成果计价，由贡献者决定以入股或债务的方式兑现，具体的入股方案和债务偿还方案参考附件；
2. 主持第一届董事会、监事会选举，提交首届董事会、监事会名单和竞聘过程中的原始文件；
3. 制定内部机构设置、管理制度、工资报酬标准，提交相对应的文件；
4. 现有团队成员未签订正式合同的，制定合同并与安排补签；
5. 整理工作记录、单据、表单，财务数据，资产；
6. 补登工作结果（包括筹备工作），其中：
       1. 合格的APP上线及以前的工作按照500%登记报酬；
       2. 100个种子客户提交定制需求至成衣交付的工作按照300%登记报酬；
       3. 100个客户的成衣交付，且退换货率低于5%，这期间的工作按照200%登记报酬；
7. 办理设立手续；
8. 市场负责人带来100个合格的种子用户，验收标准参考附件1；
9. 技术负责人完成产品原型开发的工作，通过筹备会议验收通过，验收标准参考附件2；
10. 供应链负责人提供供应商、制衣厂的合作关系并落实合同履约，验收标准参考附件3；
11. 运营负责人负责将App的相关运营指标运营至合格标准，验收标准参考附件4；

具体分工由召集人安排。

### 财务管理
1. 筹备组成员的工作支出，由筹备召集人审核后报销。
2. 筹备工作适用董事报酬标准。

### 筹备会议
1. 筹备会议固定议程如下：
       201x年a月b日：审议章程、团队成员合同草稿；审议201x年m1月d1日以前的工作记录、单据、表单、工作结果。
       201x年c月d日：表决章程、团队成员合同；审议内部机构设置、管理制度、工资报酬草稿；审议201x年m1月d1日以后的工作记录、单据、表单、工作结果。
       201x年e月f日：表决内部机构设置、管理制度、工资报酬；检查设立手续相关材料及结果证照。
    【具体议程根据情况设定，尽量明确。】召集人提前3日通知可以召集临时会议。会议内容在会前2天发给所有成员。
2. 筹备会议采用罗伯特议事规则。表决实行1人1票制，投票分同意、反对票，不设弃权票。计票采用简单多数规则。
3. 涉及具体工作的动议，应明确预算、时间要求、工作结果，明确验收标准和奖惩。
4. 筹备会议应当制作会议记录。形成决议的，应当当场制作会议纪要，并由出席会议的筹备组成员审阅、签名。

### 工作透明度
1. 筹备组的工作信息公布在：Github上为筹备工作准备的专项目录。
2. 筹备组成员名单、新成员加入、成员退出等事件当天公开发布。
3. 筹备会议的会议通知、会议记录、会议纪要均在当天公开发布。
4. 召集人安排的具体分工，当天公开发布。

 签名：【全体团队成员签名】
===========================================================

附件1
E方完成》100，《500种子用户，则获取对应3%的收益权；E方完成》500，《1000种子用户，则获取对应5%的收益权；若种子用户的有效性未被D认可，则扣除对应种子用户数*3的股份；
附件2
D方和F方协商产品原型开发的需求清单和验收标准，D方将10万元的开发预算成立一个信托基金，并找双方认可具备评估能力的第三方来做合同验收人，验收人可以拿到1万的报酬，由D方支付，F方完成本合同约定的工作内容后，第三方评估通过支付费用，如果没有按照标准完成开发，则支付30％的费用，D、F双方提前约定好比例，当获得投资后，双方再商谈正式加入的报酬方案；F完成的工作内容必须提交软件著作权至D，权力转移验收后方可支付报酬；
附件3
供应商提供业务需要的原材料，符合标准、市场均价和供应时间则拥有3%的股份；制衣厂根据业务需要及时制造出对应验收标准的货物，则拥有3%的股份；若未能按时提交在15个工作日以内则扣除1%的股份，若造成了对应的损失，由筹备款支付，耽误15-30个工作日，则扣除2%，超过30个工作日则扣除全部；
附件4
H为App的下单转化率状况负责，若转化率低于1%，则H拥有对应转化率的股份；若1-3%之间，则拥有转化率*1.5的股份；若3-5%之间，则拥有转化率*2的股份；高于5%，则拥有15%；如果筹委会和H均认可的专业顾问或第三方事后发现有作弊行为，则扣除对应部分*3的股份权力；顾问及第三方的酬劳为每月一次，每次评定3000元；
