### ISSUE TITLE
初创自觉共同体的部署方案

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#47]

**Comment by lidan704** [comment]
初创自觉共同体的部署方案
角色清单：股东兼董事、监事
资产清单：《公司法》、提案、章程
关键步骤：
1、股东会和董事会兼容的公司。
2、制定公司章程
3、设立部门
4、建立基本管理制度
执行要点：
1、依照《公司法》第六条到第十三条的规定及第三十条到第三十五条的规定，注册公司，行驶股东权力履行股东义务。并根据第五十条之规定，设一名执行董事兼任公司经理。根据第五十一条规定，设立一名监事。
2、公司章程及设立部门。重点履行董事和监事的职责。详见公司法董事监事职权。以执行董事替代董事会责任，以监事替代监事会责任。整两个部门职能法规运转。
3、对于提案的规定：按照每条提案1万元的价格，向公司内部及外部，收集提案。两次提案均被采纳，提案人可称为公司董事。执行董事职权。附带修改公司章程，成立董事会。
4、公司章程要点：董事会采取1人1票制，不依赖股权比例做出决策。
