### ISSUE TITLE
原始共同体成员的个人领域部署

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#51]

**Comment by lidan704** [comment]
自觉共同体个人领域部署方案
关键要点：不幻想、自检机制、基础能力
部署要点：
1完善记录不被篡改的能力。
2用《公司法》《合同法》《议事规则》《合伙企业法》为思维训练初级素材。分别在几家公司内部设立三会并保证持续运行，董事长，董事，监事，CEO四个角色扮演。熟练操作三会运转，董事会、股东会、监事会。
3个人身体健康领域部署以有效减低体重、增加野性的活动为主。
4对原始共同体工作的升级的为第一试验场。

**Comment by lidan704** [comment]
原始共同体成员个人领域部署方案
关键要点：不幻想、自检机制、基础能力
部署要点：
1完善记录不被篡改的能力。
2用《公司法》《合同法》《议事规则》《合伙企业法》为思维训练初级素材。分别在几家公司内部设立三会并保证持续运行，董事长，董事，监事，CEO四个角色扮演。熟练操作三会运转，董事会、股东会、监事会。
3个人身体健康领域部署以有效减低体重、增加野性的活动为主。
4对原始共同体工作的升级的为第一试验场。

**Comment by lidan704** [comment]
增加：1完善记录不被篡改的能力。个人共同体化的改造。
