### ISSUE TITLE
主题A：整理行为记录

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#62]
整理各阶段工作记录，按照
![工作结果发布](https://user-images.githubusercontent.com/1675665/41259061-cdf85ad2-6e04-11e8-8948-66641e0cf721.png) 步骤进行替换处理、选定内容范围。

**Comment by lidan1980** [comment]
创意产生
由于新闻报道关注项目，并与股东进行沟通，结论是此项目无法在中型及以下企业操作。
在受邀去北京某公司考察期间，从设备供应商处获得行业no.1企业的运营数据，发现此方式发展迅速。
安排相关人员进入该企业进行调研。调研结果次月进行汇总分析。
项目适合现在的发展阶段，而且是市场机会，应大力发展

**Comment by lidan1980** [comment]
试点检验
根据惯例及个人想法，发起项目试点。
组建新项目团队，确定基本薪酬绩效
设定运营目标延后一个月达成
从方案产生到落实经历至少一次反复

**Comment by lidan1980** [comment]
正式运作
个人调动分部的市场师资及社群团队设定具体运营目标
调整划定区域，以重度垂直的思维深耕一个区域的思路

**Comment by lidan1980** [comment]
结束
项目负责人未达成基本运营目标
大股东信息未披露造成失误
项目负责人以丧失机会成本为由出走另创企业
