### ISSUE TITLE
主题B：整理行为背后的思考过程

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#63]
复原行为背后的思考过程；
识别没有产生行为的心理活动；
暴露自我保护机制所干扰的记忆。

思考过程的整理结果（文件），也按照
![PSMD工作结果发布](https://user-images.githubusercontent.com/1675665/41264692-a7216806-6e20-11e8-803f-48fc70ac73c5.png)步骤进行替换处理、选定内容范围。

为个人领域模型的复原、改进提供基础信息。

**Comment by lidan1980** [comment]
创意产生背后思维

信息不对称造成的不同区域之间运营启动的时间差是制定企业发展方向的重要依据
信息成为不同股东及运营者之间博弈的筹码
区域垄断思维

反例
仅限于争夺口头胜利，对行为没有改变
产品及团队定位点较低，满足与项目启动，低水平运营带来的业务结构微调
对于核心运营人员的高度依赖

**Comment by lidan1980** [comment]
试点检验背后思维

快速推进新项目的发展，变成自留地，在企业博弈中拥有更多的话语权
检验脱离企业独立运转，并且有足够大市场的项目。

反例
对于权力问题只做了口头授权
没有规划利益模型，团队成员依照组织原有行为模式及猜测做判定
情报未及时更新，缺少体系支撑

**Comment by lidan1980** [comment]
正式运作背后思维
用局部团队造成信息孤岛，不透明，保留对团队形成误导的可能性。
反例
所有的相关权力利益未做清晰界定，动作结果不能有客观评价，只能说好，不能批评也不能形成处罚，一旦处罚，团队崩盘
依照他人对自我利益及权力的认知，形成的幻想圈，对自己的能力和团队的执行力形成判断，以此为依据确定工作方向和节奏
反例
在项目运作期间未匹配相应的网络系统支撑，只有50%的体系开跑
未经组织审核，存在制度漏洞
以此形成的惯例，下级人员会效仿
未对权力与利益进行明确，下级人员会以自己的心理契约付出相应努力并要求相应回报

**Comment by lidan1980** [comment]
结束背后思维
信任是工作结果的最好保护，缺少自我保护意识
对自我影响力的认知来源于向下的人际关系而非法定权力
反例
项目负责人，小股东，大股东三者之间没有明确的权利与利益的契约，都希望保留投机的契机。走一步看一步，尽量少的付出，尽量多的获取。
小股东自我认知存在偏差。
小股东没有足够的勇气面对大股东曾经的过错，形成书面契约，仅仅满足与口头承诺。为以后的工作埋下隐患。
小股东和大股东实际上处于同一层次
项目负责人及大股东利用小股东的认知偏误获利
