### ISSUE TITLE
主题C：模型整理

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#64]
复原事实上在使用的个人领域模型，
设计可操作的改进版本。

**Comment by hyg** [comment]
##  1 | 产品创意

### 现状
- 没有鼓励创新的权利分配规则，需要通过地盘扩张获得创新回报。
- 没有保护试错过程的权力安排。
- 以上情况不受打工或创业局限。

### 反例
- 各方倾向于搜集以自己领地为中心的新产品信息，以及其它新产品的利空信息。无人关注需要打通各部门才能运行的新产品，直到某成员逐步扩张、控制产品涉及的主要部门。
- 在领头企业完成新产品试错阶段之后，才会积极搜集信息，同时还需要物色拥有实操经验的人员，借助他们启动新产品（并承担责任）。
- 丢弃搜集到的早期信息，错失领先三四年、借机扩展一两省份的机会。试点验证结束发力扩张时，正好撞到市场天花板 -- 巨头开始进入本区域、小作坊也有能力复制这个新产品。

**Comment by hyg** [comment]
## 2 | 试点验证

### 现状
- 只验证工作流程，不验证配套的权利分配规则。试点人员在简单的临时报酬下工作。
- 只验证可以外购的软硬件，不验证自行开发的配套系统。试点人员在简单的指令下绕过管理系统工作。
- 有四套不同层级的利益分配规则，但没有配套的修订机制。未说明如何适应变化，如何保证利益不受侵犯。
- 对试点负责人口头交待工作，出现偏差后召集全体成员开会纠正。
- 有简单的股权分配比例，但没有完成出资、注册步骤。
- 没有严格遵守权利分配规则的历史记录，实际上没有按严格遵守规则安排学习。

### 反例
- 团队成员投入迟缓，执行力度不到位，甚至离队观望。
- 团队成员只想复制产品后迅速兑现利益，缺乏创新（仅仅微调）的意识。
- 因为软件部门不直接掌握，从思想上就没有考虑同步开发、验证配套系统。

**Comment by hyg** [comment]
##  3 | 正式运营

### 现状
- 口头调动人财物，安排选址建立新部门，调动其它部门人员兼职支持新产品。
- 由于IT部门属于别人地盘，新产品没有配套的管理系统，依赖excel人工汇总数据，再与原有人力、财务制度衔接。（旧业务也有10%左右数据需要人工汇总）

### 反例
大股东提出接管新产品。

**Comment by hyg** [comment]
## 4 | 停止

### 现状
- 未约定停止规则。
- 约定51%~49%股权分配。未约定认缴金额、实缴时间，每一两月商定支出预算。陆续投入五六十万（对方投入三四万、一年时间）后觉得业务没有起色，停止投入。

### 反例
- 对方以合作工作成果外出求职，提出120万年薪，实际成交40万。
- 工作成果的归属未作界定。

**Comment by hyg** [comment]
## 改进版本

### 复述
- 复述自己的行为，回忆行为背后的真实思考过程。
- 如果出现卡顿，则把这些行为列为失控，会重复发生。

### 偏差 （可能依赖PSMD受托者）
- 在流畅复述的行为和思考过程的范围内，明确预期（各人行为、第三方可观测的现实），对比出偏差。
- 估算交由其他人消除偏差的可靠方案：进度、预算、受托人、工作结果的提交和验收......。

### 动员
- 根据偏差行为的主从关系（上一级权力分配下一级的权力和利益），安排亲自纠正偏差的范围和次序。
- 根据亲自纠正偏差所需的学习、工作内容，结合规律制订计划，分配个人资源。
- 交由其他人消除偏差的，签订契约，分配资源。

### 监督
- 授权核实复述的行为和思考过程，把虚假的流畅列为失控。
- 授权检查资源调动情况，奖惩、直接调动资源。
- 在监督者本身有能力消除偏差的情况下，授权监督者检查工作结果，奖惩。

根据个人特质设计书面记录、奖惩方式和数额、监督人行使权利的具体方式。

---

当前工作重点是：
- 对外：避免重复同类人群的偏差，落入”原始陷阱“。消除团队成员只认现金、地盘（特权）的行为，扩展现金以外的利益种类，消除地盘改为可以不断重新分配权力的机制。
- 对内：根据长期利益分配个人领域的资源，根据个人资源分配制订对外契约，并且制度化。

当前工作重点解决后，还会有下一批重点问题、下下批重点问题。为了避免讨论局限于当前工作，根据所有批次重点问题的共性，使用现状、反例、统一、保护这些词汇和关系图。如果这些词汇导致当前工作重点都停滞，那就不要看它们 -- 第一批工作重点解决后，寻找下一批重点时才需要借助这个共性模型。

目前仍依赖PSMD受托者识别重点问题，共性模型暂时不作为掌握目标。

**Comment by lidan1980** [comment]
个人领域----关键能力
偏做事情还是偏做好人，偏幻想还是偏现实，偏行动还是偏语言。
缺少关键能力的保障，很难保证自己的工作的质量，以及高质量工作成果持续生效。

强度选择
控制时间
控制身体
检视状态
周期
明确目标----升级或降级触发点

**Comment by lidan1980** [comment]
身体现状：肥胖造成的问题是精力涣散，较长时间的坐着和站立都会影响注意力集中，容易瞌睡。内脏技能会受到影响，尤其是肝脏，脂肪肝。会对未来的身体健康担忧。
精力集中现状：晚上11点以后到凌晨2点半左右，有过精力高度集中，产出高质量文件的经历
反例：熬夜之后有大半天的时间低效
      加重肥胖，会放纵饮食
时间使用现状：高度分散，停留在聊天的阶段，不论是主动发起还是被动接受，无结论，或有结论无行动
反例：关键问题拖延，核心利益受到损害
