### ISSUE TITLE
讲师的行为

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#65]

**Comment by cqhwang** [comment]
### 讲师的行为

相关：[讲师的意识](https://github.com/xuemen/PSMD/issues/66#issuecomment-448472645)

> 行为主题
调研、整理分析对象的典型行为；
分析典型行为的效益。

**讨论记录**
黄常谦：
- 有较强的自我证实行为
- K12教育的老师有严格规范的考评体系
- 情报反应STEAM教师很匮乏，缺乏系统培训，缺乏标准体系
- 情报反应STEAM教师从业时间不长，容易迷茫，流动性也大

李丹：
- STEAM的讲师有一些转型或跨界的人员，整齐度比较差，定位不清晰，
- STEAM的讲师职位归属感不强，稳定性差
- 目前在教育体系内，还属于比较低价的劳动
- STEAM类型的老师议价能力低，
- 总部提供的课程水平比较低，也就是给小白用
- 某些情况老师转型教授，成就反而很大
- 老师内省比较容易，但咨询师就比较难
- STEAM教育建立一个行业协会也许是有价值的
- 个体户老师不容易对平台提供的公共服务买单
- 教师个体基本就是强者恒强弱者恒弱

黄勇刚：
- 我接触的STEAM讲师和投资者之间有互动，希望获取机会有人为自己筑巢，但未必控制权力
- 相互之间搞的各种中心比较容易离析
- 课程设计师和讲师之间是师徒关系，但市场上被小白抄袭多，造成课程设计师动力不足
- 和强者合作困难是在明处，容易评估

**思考：**
- STEAM老师师傅带徒弟也许更有价值，关键看续费率
- STEAM老师需要综合性知识运用能力较强，除编程类的
- 需要企业有很强的运营和识别能力

**Comment by lidan1980** [comment]
讲师行为：
1、因为没有足够的激励体系，教师并没有动力研发课程；
2、讲师希望获得尊重，并不希望参与人力资源市场组织的活动中；
3、讲师在行业初级阶段议价能力比较弱；
4、不要通过整理行业的弱者，进行获利。

**Comment by lidan1980** [comment]
讲师行为：
1、因为没有足够的激励体系，教师并没有动力研发课程；
2、讲师希望获得尊重，并不希望参与人力资源市场组织的活动中；
3、讲师在行业初级阶段议价能力比较弱；
4、讲师授课的质量由续班率评估，行业的续班率和产品的刚性需求有关，家长到了课业压力大的时候会选择放弃。讲师的学生带生数量无法实现累计。
5、课程产品以项目制为主，缺乏连续性，讲师所带学生数量累计较为困难。
