### ISSUE TITLE
讲师的意识

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#66]
- [ ]

**Comment by cqhwang** [comment]
### 讲师的意识 

相关：[讲师的行为](https://github.com/xuemen/PSMD/issues/65#issuecomment-448433891)

> 意识主题
调研、整理行为背后的思考过程；
思考过程中的偏差；
估算这些偏差的障碍；
部署者消除这些认知障碍的方法。

**讨论记录**
黄勇刚：
- 作为部署者，王牌教师的自立山头，如何消除？

**部署者消除这些认知障碍的方法**
李丹：
1. 共同体需要识别讲师是否有能力自立山头
1. 对于有能力者可以投资参股，辅助建立分支机构
1. 没有能力者需要劝导，帮助其认知困难或指导提升路径 
1. 共同体与教师考评标准机构合作，可以帮讲师做荣誉标记，也是吸附讲师的手段

黄常谦：
1. 类似于建筑施工行业的挂单包工头，与企业之间用契约合作。类似于市场与雇佣两者的中间模式
1. 对比其他地区或行业，行业协会可以约束准入门槛，并且约束从业人员的一些不良行为，但有待这个模式的诞生。

黄勇刚：
1. 行业精英创立的行业协会或智库机构，可以标记从业人员的成长模型，并且提供支撑，也包括对整个行业的发展做支撑，这是未来一种趋势。

**Comment by cqhwang** [comment]
### 总结

- 需要建立王牌教师识别机制，公开透明的可实时计量的奖金制度，以及职业上升规划
- 需要数学分析教师人力成本增幅对收益影响的模型，当盈利与奖金接近时需要调整合作契约
  1. 调整合作契约可以采用长期激励的股权（内部契约升级）
  1. 与其成立合股分支机构（股权合作模式）
  1. 给予特许经营权并收取费用（市场化模式）

**Comment by cqhwang** [comment]
### 补充：意识主题

> 调研、整理行为背后的思考过程；
思考过程中的偏差；
估算这些偏差的障碍；
部署者消除这些认知障碍的方法

- STEAM教育成熟度不足，从事的讲师与K12比较缺乏从业信心
  **方案**： 
1. 注意师傅带徒弟的模式，有精英师傅教授的徒弟一般会有成长信心
1. 师傅的自研课程，由徒弟传授，课程的提成交由师傅分配。徒弟认为师傅自研课程效益不高则不会接受，激励师傅进行改良。师傅自研课程需要推广获取收益，则需要传授和激励徒弟。
- STEAM非刚性需求及续班率低，造成讲师能力不易实证（如因课业压力家长退课）
   **方案**：
1. 销售与客服需要将家长纳入识别信息，辨识家长的影响要素
1. 每月组织讲师进行技能考核，分值列入月度激励考核参数
1. 每月组织一次K12教育数学教师与编程讲师联合备课，根据K12教学进程，同步解决数学课件与编程课件的逻辑关联，加强学生在编程学习与数学学习之间的互补。
- STEAM课程系统不成熟，缺乏连续性，讲师的绩效考核不如K12完善，在能力的认知上其自身与共同体之间容易产生偏差，造成离职。
   **方案**：
1. 需要关注行业情报，加强行业交流（参与行业协会），识别行业精英，形成共性的讲师能力模型与成长体系
1. 建立讲师培训公积金，激励讲师参与培训

- STEAM教育未有成熟的职业认证体系，个人议价能力差，参与人力资源市场欲望不足
   **方案**：
1. 引入师傅带徒弟模式，与行业精英联合，参与行业协会
1. 讲师获得协会（行业）认证的在薪酬中设置加权参数
