### ISSUE TITLE
课程设计师的行为

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#67]

**Comment by cqhwang** [comment]
### 课程设计师行为

相关：[课程设计师意识](https://github.com/xuemen/PSMD/issues/68#issuecomment-448537610)

> 行为主题
调研、整理分析对象的典型行为；
分析典型行为的效益。

**讨论记录**6:30-7:30
李丹：
- 原创课程非常少，目前少儿编程普及率5%，美国英国比较强，我们多数是模仿他们的课件，可在网上找到
- 童程童美、小码王、编程猫是比较有规模的，模仿研发的课程比较多，
- 童程童美在国内的团队研发多，人才也被挖得多，采用项目制的研发，
- 童程童美的这种研发，其研发成果平行的多，不能完全体现能力等级，容易造成续费率低
- 机器人等教学更没有标准，倾向与实验，以玩为主。
- 乐高、乐博、能力风暴都属于产品销售为主，其实亏损很多，关键在课程体系不容易建立
- 参与体验课程的人多，真正花钱的消费者并不多
- steam课程和其他比，课程的设计差太远了，师徒继承代际相传差。
- 还有一种是高中的竞赛路线，部分来自现实中的研发和学习培训结合，走拿奖路线
- 还有一些跨界人才，自己做课程，有爱好有激情有灵性，但缺乏系统性，也是一种选择

黄勇刚：
- 关注群内的：符美瑜 吴俊杰 张路，三位
- 符是典型老师，他们的行为是体系内老师的典型行为，报课题、出论文、带徒弟
- 吴的成果市场化比较强，是国内比较典型的推动者，在华东华北活动多，也力求产业化，但在原始生态位，有专业能力，需合作能力。
- 张路 目前还很活跃，搞夏令营，免费寄课件资料，是个搞企业的CEO
- 总的来说，这些人物都有业务能力，甚至和国外一线都能持平，但合作能力差



**归纳**
- 课程相似性多，同业交流也多，但相互未必认同
- 在STEAM课程体系上，也许需要附属教育体制
- 各精英在课程设计上，也许来自一个原创（如国外）
- 力求市场化的课程设计者也很多，联合合作难
- 整体状态：有个人热度、区域品牌效应
- STEAM课程设计是需要精英和有知名度的老师

**讨论总结**
1. STEAM教育课程设计目前尚未形成体系化，未出现主流产品
1. 领域内有不少精英在努力研发课程体系，横向也有交流，但合作与联合不足
1. 部分已实现产品化，有品牌效应，当然模仿国外或源自国外的也不少
1. 和体制内接轨的课程主要体现在竞赛上，受到学校的重视与参与有关
1. 课程设计上有个人（精英）热度现象和区域效应

**Comment by cqhwang** [comment]
### 总结

- 课程设计师的成果是共同体核心竞争力，部署者需要对市场及该角色进行深度思辨，并具备前瞻眼光，设计出多种部署方案，例如：
1. 内化在企业的雇佣模式，适合模仿创新，成熟品种的简单调整
1. 市场化的订制或委托模式，适合创新力度大的品种
1. 联合运营分成模式，设计师出产品，共同体负责销售运营，适合需求能力互补的设计师
1. 股权合作模式，需要注意设计竞争与淘汰的机制，防止永久占据权利
- 共同体可以参与课程设计师个体能力之外的公共领域运营管理，为设计师提供能力标记，例如：行业协会、行业标准委员会、竞赛委员会等
- 共同体可以主导或参与，联合行业企业建立与运营课程创新产品的共享经济平台，获取线上运管收益，实现线上与线下的交互导流

**Comment by cqhwang** [comment]
### 补充：行为主题

> 调研、整理分析对象的典型行为；
分析典型行为的效益。

- 原创课程非常少，课程设计师对研发的收益信心不足，模仿行为多
  **分析**：经过情报收集，全球范围STEAM课程存在模仿相似的特征，其中很多属于硬件产品配套的课程，受众面也比较大。从效益出发，认同进过思辨的高水平模仿属于正向行为。

- 市场上课程相似性多，同业交流也多，但无法形成稳定的联盟，相互缺乏协同
  **分析**：硬件产品的差异化竞争影响到配套课程的协同，行业成熟性不足也会造成此现象。需要关注行业标准化进程，行业联盟的发展等，防止课程设计偏离主流。

- 比较热衷于竞赛的参与，通过竞赛成绩使自己的课程设计获得标识，也容易获得学校的合作
  **分析**：从讨论及情报获知，产品厂家、课程设计精英、学校均热衷于此。有利于品牌和续费，可积极参与，建立区域的选拔赛，培育选手，参与省级和国家赛事。

- 部分课程设计的精英，有个人热度现象和区域影响效应
   **分析**：课程设计对品牌和续费有帮助，应识别课程设计精英积极吸纳参与，或招募其徒弟参与，保持与前沿领航者的关系。

- 情报反应，STEM课程起源可能是德克萨斯大学奥斯汀分校在1997年设立的UTeach项目。在国内STEAM教育的课程设计师除产品商培育外，不少是师傅带徒弟培养出来的。[《美国STEM教师的培养及其启示》](http://www.doc88.com/p-7458487992696.html)
  **分析**：在STEM教育方面，美国有多项立法法案，需要关注课程设计的溯源，沿用其标准，不偏离主流。
