### ISSUE TITLE
课程设计师的意识

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#68]

**Comment by cqhwang** [comment]
### 课程设计师的意识

> 意识主题
调研、整理行为背后的思考过程；
思考过程中的偏差；
估算这些偏差的障碍；
部署者消除这些认知障碍的方法。

李丹：
1. 从大学或著名大学出来的研发团队，有很强的研发意识，有成功者的幻想。可以在研发产品上有帮助，但大部分不是好的合作伙伴，适合契约关系。
1. 在精英教育到来之前，会有一些分散的专业精英在做这些研发，部分成果可以利用
1. 某些机构的课程设计师是师傅带徒弟的方式
1. 还有一种课程设计师是出产品结构的，类似项目经理
1. STEAM老师非常依赖产品设计者，这点有别于K12教育
1. STEAM优秀学生是课程设计师的主要目标

黄勇刚：
1. 专业领域的精英未必是真正的精英，无法实现组织化
1. 大型企业内部可以建立师傅带徒弟的研发团队，但STEAM还未形成规模，如何跨企业建立研发？
1. 复盘STEAM过往，出现过几次？怎样的稳定状态？
1. 关注[《消费合作社》](https://baike.baidu.com/item/%E6%B6%88%E8%B4%B9%E8%80%85%E5%90%88%E4%BD%9C%E7%A4%BE)

**部署者消除这些认知障碍的方法**
1. 建立利益分配方案，在培训机构外建立独立的研发组织
1. 互联网平台模式，由平台负责为独立的课程设计师销售与运营，由平台分配利益给设计师，具体线下部分的运营交给加盟机构，收取加盟费，也为平台导流
1. 通过竞赛吸引课程设计师来对选手研发，转化出产品，优秀生资源与课程设计师交互升级
1. 精英家长或精英学生家长的社交群，对课程创新需求而调动课程设计师资源

**Comment by lidan1980** [comment]
课程设计师意识：
1、案例：由于无法确定自己的课程是否能够给自己带来足够的收益，所以课程设计师并没有全部的精力投入到课程研发上，基本上会进行拼凑或者模仿成品。
方案：在共同体内部实行师傅带徒弟，徒弟收益和师傅挂钩的办法。课程设计师带领讲师开发课程并培训他们，根据他们的招生量和满班率续班率等指标或者自己的收益。本身自己可控。
2、案例：课程设计师优劣的标签是学生的成绩。
方案：在局部范围内尽可能多的获得优质学生，由课程设计师带尖子班，成就感强，增加自己未来的议价能力，会全力做好课程开发和带好课程；
3、案例：课程设计师之间无法形成稳定的联盟，相互之间缺乏协同。
方案：组织相关竞赛，课程设计师成为竞赛内容的研发者，或者是评价者。以这样的方式替代行业协会的模型，由于竞赛结果和升学及评价相关，用户群体稳定，课程开发者也会在竞赛前后产生高度的协同。
