### ISSUE TITLE
销售的行为

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#69]

**Comment by lidan1980** [comment]
销售行为：
1典型行为：提出缴费要求的语言习惯；课程和需求结合点的熟练；竞争对手信息获取及对策应用；
2销售三种类型：善于获客，勤快（笨）；善于签约，灵活（贪）；善于服务，亲和（弱）。市场、签约、客服。
3争夺有限的资源是销售工作贯穿始终的行为。topCC大部分都是用资源养大的。资源包括优质教师的优质时间段，更多的上门用户，更多的外呼电话量，更多的来电接听机会。
4两个或以上销售把业绩转给一个人以获取更高额度的提成。
5离职时把潜在用户资源带走。
6对用户承诺过度，超额赠送，违规签单。
