### ISSUE TITLE
销售的意识

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#70]

**Comment by cqhwang** [comment]
### 销售的意识 

相关（[销售的行为](https://github.com/xuemen/PSMD/issues/61#issuecomment-448065729)）

> 意识主题
调研、整理行为背后的思考过程；
思考过程中的偏差；
估算这些偏差的障碍；
部署者消除这些认知障碍的方法。

**讨论记录**9:45~10:14
李丹：
- 个人驱动力：赚钱的动机，成果意识
- （在群里贡献：九篇个人销售方面讲座）
- （在群里贡献：咨询流程及管理机制）
- 工作记录、历史版本需要保留，提升制度的依据
- 一些细节设计很重要，例如与客户回访记录、录音，主管旁听销售的过程记录等

黄勇刚：
- 部署者真正值得研究的是角色主动力，而不是被动的行为
- 怎样强化他的职业角色？这是部署者的主要思考
- 李丹提供的规章与思考细节，是部署者需要的素质
- 权力部署中是否有部署针对销售的不断更新？

黄常谦：
- STEAM的销售有岗位跨界现象，如老师兼销售等，
- 销售个人训练的意识很重要，如市场广泛的“狼性文化”

**部署者消除这些认知障碍的方法**
1. 共同体在销售上建立一种范式，对销售的帮助很大
1. 历史记录、细节思考对销售制度的升级很有帮助
1. 销售是一种和顾客的心理对抗，人的意识行为很重要
1. 销售的修订行为需要在共同体权力部署中约定

**Comment by cqhwang** [comment]
### 总结

- 对于纯销售专长的人才，部署者需要思辨短期激励与长期激励（特别是股权）的权重组合，避免角色获得长期激励反而影响其贡献值的降低
- 对于教学与销售结合的人才，部署者可以考虑其向分支机构负责人提升，逐步靠近权力中心
- 激励成本提升接近效益归零，可以考虑承包模型、独立子公司、特许经营等更加市场化方向

**Comment by cqhwang** [comment]
### 补充：销售意识

> 调研、整理行为背后的思考过程；
思考过程中的偏差；
估算这些偏差的障碍；
部署者消除这些认知障碍的方法。

- 激励模型让销售的意识专注于实质效果，但个性偏差会反应出不同的沟通特质，如“善于获客，善于签约，善于服务”
  **方案**：细致识别个性偏差，部署差异化销售岗及对应的激励制度，例如：市场、签约、客服

- 销售成员会共同认识到可掌握的资源有限，相互间会有竞争，协同的目的也许是获取最佳提成
   **方案**：
      1. 识别与修订激励制度的偏差
      2. 激励模型可设计为个体或小组双模式，销售员可选择适合的模型
      3. 提升销售对市场的感知能力，反馈销售激励制度升级

- 销售会识别每个客户的价值，努力实现对客户可控成为自己的资源，成为职薪议价条件甚至离职时带走客户
  **方案**：
      1. 强化品牌，课程，王牌教师的传播，防止销售的离心效应
      2. 专注客服的信息反馈，及时发现和纠正偏差，不断升级客服工作模型
      3. 识别王牌销售，部署短期激励与长期激励（例如股权）的权重组合

- 为实现对客户资源的控制，有可能最大化使用优惠权限，甚至超额赠送，违规签单
   **方案**：
      1. 多渠道强化客户沟通，协助销售增加客户粘性
      2. 精细化客户识别，建立同样成本下对应的多种优惠模型
      3. 专注市场情报，及时升级优惠模型
      4. 专注同样成本下，优惠权限与销售激励的组合模型
