### ISSUE TITLE
校区负责人的意识

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#72]

**Comment by cqhwang** [comment]
### 校区负责人的意识

相关：[校区负责人的行为](https://github.com/xuemen/PSMD/issues/71)

> 意识主题
调研、整理行为背后的思考过程；
思考过程中的偏差；
估算这些偏差的障碍；
部署者消除这些认知障碍的方法。

黄常谦：
- 个人经历中对比这个角色有点类似非法人的分公司经历角色
1. 处于权力的夹缝中，一方面要满足共同体运营指标，另一方面希望建立自己的权力中心
1. 如果团队的人力资源不可控制，意识中会建立自己的隐形权力圈子
1. 为保护自身利益，会对共同体屏蔽对自己不利的信息
1. 容易抗拒共同体风控制度的管理，常规部署中这些制度主要约束对外合约
（案例：浙江某两个建筑施工企业在外阜发展的模式）

**部署者消除这些认知障碍的方法**
1. 部署者需要解决这个角色的上升通道，或岗位提升，或长期激励，或与其在指定区域联合创业（升级为法人子公司）
1. 部署中需要通过逻辑分析，交叉印证信息的准确性
1. 建立这个角色的个人领域模型并纳入监控识别，提高激励的及时性和准确性
1. 提高总部的服务能力， 增强总部的研发能力
1. 分支机构需要总部具有融资接口，为分支机构输血

**Comment by cqhwang** [comment]
### 总结

- 研发多种分支机构的部署方案，让校区负责人角色具备多种选择，例如：非法人分公司、法人子公司、承包经营、特许经营等
- 需要关注区域市场竞争状态，及时调整具备应对特长的校区负责人，例如：进攻或防守、开源或节流
- 加强内部运营的信息收集与分析能力，建立对分支机构的纠错模型，提升效益降低风险，增强对共同体依附性
- 识别分支机构的共同需求及对应成本，内化到共同体作为公共服务支撑，并持续提升效益，达到比竞争对手更加优化的成果，同时也加强了分支机构对共同体的依附性
- 共同体持续创新，为各个分支机构提供领先对手的产品支撑
- 共同体关注战略，为各个分支机构提供领先对手的策略支撑
- 建立多种融资模式，为区域分支机构提高抗打击能力及兼并拓展能力
