### ISSUE TITLE
家长的行为

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#73]

**Comment by cqhwang** [comment]
### 家长的行为

相关：[家长的意识](https://github.com/xuemen/PSMD/issues/74)

> 行为主题
调研、整理分析对象的典型行为；
分析典型行为的效益。

**讨论记录**
黄常谦：
- 家长是少儿教育的消费者，某种程度上是被迫消费者居多
- 家长对于补课类的产品被迫消费较多，原因是应试教育的博弈模型
- 在steam上通过交流获得一些消费家长的信息（待补录）
- 部分家长对孩子不得不补课有同情心
- 局部区域内，受品牌影响大，家长群体消费的现象不少

黄勇刚：
- 符美瑜老师用编程方法教数学，有创新，联通了STEAM和数学
- 家长是恐慌、攀比，被厂商诱惑，拼装备，但实际价值不高
- 一线城市的家长大部分都是这样成长的，会对孩子依然套用自己的成长模式，有主动性

李丹
- 有的家长对孩子学习不会感觉心疼，而是更加主动
- 孩子补课的消费决定权主要在孩子父母，爷爷辈干预不多
- 在身边少时间少的父母，花费补课的意愿更强
- 家长群的焦虑情绪对产生消费有帮助

**Comment by lidan1980** [comment]
家长意识：
1，家长需要一个评价标准，进行导向，增加粘性；
2，家长接受竞赛给孩子在升学和评价上的作用；
3，家长功利性相对较弱；
4，家长对便利性的要求和体系要求比较高。
5，由此成立的比赛可以采用psmd操练的模型保证公正性，先进性和稳定性。
6，培养孩子成为精英是家长的愿望。

**Comment by cqhwang** [comment]
### 总结

- 部署者可以对家长这个角色重新定义，不仅仅是消费者，例如：
 1. 识别除其自己消费之外的其他贡献因素，有增效成果的，可以设计贡献值给予激励
 1. 设计自然人债权投资接口，对家长作为债权投资的，给予特别激励

**Comment by cqhwang** [comment]
### 补充：家长的行为

> 调研、整理分析对象的典型行为；
分析典型行为的效益。

- 希望尝试孩子多元化的素质类教育，如果感觉没有天分，最多保留到小学三年级，然后转向课业。
   **分析**：和教育体制相关，随国家政策转变会有所改观，与本土K12学校联合会改善区域整体市场
- STEAM类型上，家长场地的距离远近是一个重要考量。
   **分析**：家长观念中认为STEAM教育类似游戏，并不注重跟随老师而是就近方便。需要关注体系化的课程，对孩子能力成长有明确标记
- 家长本人从事与STEAM相关行业的，家长长期不在孩子身边的，比较关注孩子在这方面的培养
   **分析**：在销售方面，有必要建立对家长的分析与识别模型，提高签约率。特别是家长从事行业相关，或家长成长中受过此类教育的，参加过此类竞赛者。
- 家长比较关注素质类教育的级别证书与竞赛成绩
   **分析**：证书与竞赛是关键能力标记，需要关注主流动向，联合主流组织部署线下区域市场
