### ISSUE TITLE
家长的意识

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#74]

**Comment by lidan1980** [comment]
家长意识：
1，家长需要一个评价标准，进行导向，增加粘性；
2，家长接受竞赛给孩子在升学和评价上的作用；
3，家长功利性相对较弱；
4，家长对便利性的要求和体系要求比较高。
5，由此成立的比赛可以采用psmd操练的模型保证公正性，先进性和稳定性。
6，培养成为精英是家长的愿望。

**Comment by cqhwang** [comment]
### 家长的意识

**讨论记录**

李丹：
- 在K12之前是希望孩子多元化成长的，素质类教育。最多保留到小学三年级，然后转向课业。
- 主要焦虑来自孩子的素质教育目标没达成，转向应试教育
- STEAM类型上，家长场地的距离远近是一个重要考量，老师反而其次。学科类则跟着老师走。
- STEAM类家长和老师的亲密程度也比学科类的低
- 竞赛是很有力度的手段
- 未来精英教育会是一个很大的增长市场

黄勇刚：
- STEAM类通过竞赛（省级市级）给学生打标签，比老师的标签更重要（评比优秀老师）
- STEAM是容易做出自动化标准的先天优势，与美术音乐不同，可以实际自证公平
- 精英型的家长会有STEAM教育的需求意识，权重比较大

黄常谦：
- 非常希望培训实现明确的成效
- 很多家长自身不能评价培训效果，主要依赖培训机构测评或学校考试成绩
- 消费意识被学校老师诱导和家长群诱导的比较多
- 一旦产生消费并产生效果，容易有依赖心理
- 激烈竞争的升学环境造成家长焦虑恐慌心态，特别是自身工作压力大的家长

**部署者消除这些认知障碍的方法**
1. 有权威性的评价对家长认知有很大的影响力
1. 素质类教育，竞赛是大部分能接受的成效标记
1. 制定升级评价标准体系在素质教育中是最具有价值的
