### ISSUE TITLE
投资者的行为

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#75]

**Comment by cqhwang** [comment]
### 投资者的行为

相关：[投资者意识](https://github.com/xuemen/PSMD/issues/76)

> 行为主题
调研、整理分析对象的典型行为；
分析典型行为的效益。

**讨论记录**

黄常谦：
1. 商业模式很受投资者关注，目标还是投资收益
1. 了解到的steam投资人本身也是从业人员，近三年有风投进入
1. 情报反应纯教学服务类的投资人自身也在不断革新，毁誉掺杂
1. 情报反应比较稳定的是实物产品生产企业，不断在升级产品，带动服务的升级
1. 投资人需要安全感，安全感需要看到“企业明文明帐的内部治理”
1. 企业能给投资人安全感核心在顶层架构，真实历史记录，最根本在于人

李丹：
1. 对这类项目来说，投资人很多，风口期基本已经过了
1. 投资机构具体的行为来说，先寻找标的，考量团队，以攻击性行为为主，
1. 投资机构受他们运行机制的影响很大，投委会决策，收益损失的分配方案非常明确，设计对赌条款进攻
1. 有一定成熟团队基本无法和投资机构的治理匹配，基本是原始生态位的
1. 就事论事，大资本参与纯投资的机会不大，更多是合伙人参与进来
1. 如果企业可以经历这个过程成长，就算历练出来了，能力提升很大
1. 某些小资本投入，没有章法的反而会是灾难性，决策效益不佳，但会负面影响团队

黄勇刚：
1. 纯投资人与企业也是门当户对的
1. 投资人和创业团队真正比较的还是认知能力
1. 清晰准确的分析投资者的行为和意识，在模型中清晰定义投资人的岗位，例如1609模型
1. 到底是产品为中心，还是内化的金融为中心，看怎样设计了，最后的决定因素就是人，利润就是这么多，看放到哪里
1. 投资人对原始状态的但有能力的创业者，就是督战队。对正规化的队伍就是另一种模型了
1. 还有一类投资人是产品企业，以投资实体与推广投资进行比较
1. 创业团队需要准备与各类投资人的业务接口
1. 投资人对内部治理最关心回报保证（保护未兑现利益），如何隔离风险？

**总结**
投资人既是“吸血者”，也是“督战者”

**Comment by cqhwang** [comment]
### 总结

**内部投资人**
> 推演：针对steam和少儿编程两个现实项目，需要持续保持核心竞争力，对应的股东会作为权力机构也需要不断的学习和升级，如果失去公开竞聘接受监督奖惩以及优胜劣汰的部署，导致依靠历史贡献就长期占据权力中心，最终共同体失去核心竞争力及重构能力。

- 部署者方案：
1. 根据业务特征分化板块，分立多个企业，适当的交叉持股，各自能够独立成长，个别偏离严重的也可以重构或解散。发展到适当时机可以加强内化成为集团企业，或者局部甚至整体进行重构升级
1. 部署[双层股权结构](https://baike.baidu.com/item/%E5%90%8C%E8%82%A1%E4%B8%8D%E5%90%8C%E6%9D%83/15482292?fr=aladdin)，同股不同权，赋予管理层较大的权重
1. 利用[公司法第七十一条第四款](http://www.npc.gov.cn/wxzl/gongbao/2014-03/21/content_1867695.htm)，降低股权转让条件，适应竞聘产生的管理层变化
1. 内部发行债券，分离短期利益与长期利益，让竞聘进入权力机构的精英获得长期利益，投资人短期利益通过债券获取
1. 成立有限合伙制企业100%控股经营企业，竞聘选举在合伙人企业进行，适应权力机构的理性更替

**外部投资人**
- 债权融资优于股权融资，不会干预治理结构
- 部署完成后要不断识别偏差，纠正失误，提升对外部融资议价能力
- 借助融资行为对内部治理进行识别，依靠内部不可干预的第三方尽职调查对部署改良
