### ISSUE TITLE
投资者的意识

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#76]

**Comment by cqhwang** [comment]
### 投资者的意识

> 意识主题
调研、整理行为背后的思考过程；
思考过程中的偏差；
估算这些偏差的障碍；
部署者消除这些认知障碍的方法。


黄常谦：
1. 信息不对称容易造成投资人意识偏差
1. 投资人风控管理的自身缺陷会过度干预融资人的部署

**部署者消除这些认知障碍的方法**
- 债权融资相比股权融资对企业的部署影响更小，不需要通过股权约束权力机构
- 创业团队没有老化现象，部署者可以提出方案，用企业借债而不稀释股权，也不必个人借债

**Comment by lidan1980** [comment]
投资者意识
1、案例：股权稀释带来创业者动力不足，在被投资的共同体外围成立新的共同体获得收益；
方案：创业者核算自己的权力底限，利用同股不同权的办法保证公司的实际控制权；共同体以公开竞聘的方式，保证运营效率，以投资协议中的对赌数据为基础，明确约定，竞聘周期；
创业者核算自己的投入及收益比，当投入和收益比下降到自己不能承受的范围时，放弃企业控制权，保证过往收益的获得。可以按照共同体估值的折价兑现离场。
2、案例：对赌协议无法完成，创业者拿不出协议赔偿资金，投资者受损失，共同体受损失。
方案：投资者兑现的现金和创业者兑现的股票，同时放在信托，在一方未履约的情况下，可以按照约定收回兑现的现金或者兑现的股票。
3、案例：投资者需要项目来进行新一轮募资，创业者与投资者共同吹大泡沫，危害共同体长期利益。
方案：创业者完善个人领域模型，核心资源及核心机制的设计能力提升。对未来三年的核心目标及为此付出的改变有清醒的认知。
