### ISSUE TITLE
部署者的行为、意识和个人领域模型

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#77]

**Comment by cqhwang** [comment]
**创立共同体的部署者**
- 部署者通过内省修炼自觉意识是基础
- 反应在个人领域就是理性化调用个人资源
- 个人理性化指导的行动是提供给共同体的实证
- 在上述基础上通过契约接受共同体权力委托实施部署
- 公平公开，接受监督与奖惩是创立部署的契约原则

**Comment by hyg** [comment]
## 行为
1. 正面：分析各角色的行为、倒推出行为背后的思考过程、定位失控环节，根据消除（行为与意识）偏差所需选定共同体的模型、设计部署方案，设立共同体并实现效益、分配利益。
1. 负面：
    - 搜集先进治理方案中的关键词汇，直接讲演架空的原则和愿景。先夺得权利再寻找机会把工作分配给其他成员，如果其他成员不接受或无法完成，宁可放任核心部门陷入瘫痪、共同体陷入割据，更关心扩大自己在割据中的势力。
    - 强调自己已经完成先进治理方案所需要的能力准备，工作中暴露真相时，宁可牺牲按规律学习、实践、提高的机会，也要把职能空转解释为其它原因。

## 意识
- 由于元认知深度不足，无法察觉其他成员思考过程中失控环节，错过早期干预机会；
- 行为偏差出现后纠偏成本已经大幅上涨，超过纠偏对应的利润增量，不得不接受既成事实，转而在较低利润水平下争夺内部权利；
- 久而久之，失去（或无法养成）创新所需的治理能力，主要治理有意识的营私舞弊，难以纠正下意识的行为偏差。失去进入较高利润的创新试错阵营的机会，陷入较低利润的跟随者阵营。
- 对外跟随行业整体周期增长、萎缩，对内自我包装、维护既得利益、阻断良性竞争。个人的中长期规划无所依附，短期工作的长远价值也失去标准，无法完成自我动员，只能专注于短期投机。

## 个人领域模型
### 主设定
1. 虽然秋季封闭讨论起草了[委托合同](https://gitee.com/hyg/PSMD/issues/IMY3M#note_1047296)，但委托者在现实中不会使用它。
1. 每次集结（封闭讨论、集中课题研究）的最后一天开始能认知现实、下决心遵从规律改变生态位，离开后挣扎两周，之后重新陷入短期投机。直到下一次集结。
1. 对受托者：过滤、截留、修饰实际工作中的情形。对团队伙伴：过滤、截留、重新组织（篡改）委托者的工作。

### 备选设定
1. 与其他部署者共建俱乐部，参考PSMD项目标准组织封闭讨论，优化部署方案，监管成员的工作。
1. 选定监督者并签署委托合同。

### 模型主要内容
1. 受托者通过在线咨询和集结推测委托者的真实工作情形，选取其中的重点、难点、疑点作为讨论主题，按照学习规律、以每次集结最后一天为有效学习时间安排解决方案，并向委托者提供自检清单。如果自检清单能有效阻断负面行为，但委托者没有使用，则受托者不再提供。
1. 委托者决心设立监督者时，签订委托合同并把实际运行记录发给受托者。受托者向监督者提供判定标准。直至委托者对监督者的委托合同失效。
1. 委托者需要专门环境和支撑服务时，可与其他部署者共建俱乐部。将俱乐部章程和实际运行记录发给受托者，根据其中问题安排在线咨询或非标委托。俱乐部有效运行一年的，受托者将其纳入标准模型之内。
1. 如果以上三项机制都失效，重大利益事项出现危机（或机遇）时提出非标委托。
