### ISSUE TITLE
复习和运用

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#79]
1. 总结人列出历次封闭讨论和集中课题研究中负责的主题，受托者补充；
1. 总结人复习各主题内容，根据当前情况修订；
1. 当晚20~24点将修订版发给相关人，收集反馈；
1. 制定后续投入实践的具体计划，明确检验事项。

**Comment by hyg** [comment]
补充：
2016年秋主题B《根据业务定制的财务制度》 https://github.com/xuemen/PSMD/issues/3
2017年春一主题B《职工参与机制》 https://github.com/xuemen/PSMD/issues/12
2017年春二主题C《以股权引入人才 》 https://github.com/xuemen/PSMD/issues/22
2018夏季主题D 《权力、决策、监察部门人员的能力和承诺》https://gitee.com/hyg/PSMD/issues/IMY3K

**Comment by lidan1980** [comment]
2016年秋主题D：局部独立核算激励方案
2016年秋主题G：核心团队与共同体的交易
2017年春季第二次 局部激励方案引入人才
2017年春季第二次 核心团队与共同体的交易
2017年秋季   初创自觉共同体的部署方案 #47
2017年秋季 改造原始共同体的部署方案 #50
2017年秋季 原始共同体成员的个人领域部署 #51
2018年夏季  整理行为记录 #62
2018年夏季  整理行为背后的思考过程 #63

**Comment by hyg** [comment]
补充：
2016年秋季主题A《创始人的安全感》https://github.com/xuemen/PSMD/issues/2

**Comment by lidan1980** [comment]
2019/3/28  23:36
复习与运用：
1/PSMD项目在过去三年在实践中应用不足。
2/依据过往经验，总是在回去后就被琐碎的事情冲击，无法深入学习和复盘，对核心问题投入时间不足。
3/参加封闭实训的准备不足，核心问题随意，增加了识别和辨析的时间成本，50%以上的时间无法发挥价值。
4/由于知识缺乏，准备不足，挤牙膏式的输出的内容质量不高。
5/明确关键动作：调动人力和财力的工作，分配权力的工作
6/明确时间周期：根据4月份自己实际能够投入的时间，估算未来三个月内的补课进度。

**Comment by hyg** [comment]
补充：
2018年冬季《部署者的行为、意识和个人领域模型》 #77 
尤其是主设定部分。
