### ISSUE TITLE
一体化方案

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#80]
1. 调研委托者在重大权利分配中的准备工作和谈判过程；
1. 根据委托者实际行为，设计业绩提升阶段的个人股权、骨干股权、提成一体化方案；
1. 提出当晚20~24点协商内容，跟进收集反馈；
1. 根据委托者协商反馈，设计新共同体部署早期的准备方案。

**Comment by hyg** [comment]
## 3.26.
### 15:44
选择一套骨干持股的制度，设计完善它，并推演提案、讨论、表决中的反对意见。以便观察这个方向的设计和运用能力，筛选实际能守住的目标。

以《分公司经理合伙制度181220.doc》为基础。
- 4. “增加条目“考核利润”分公司产生的直接利润。” --> 集团开支不算做分公司成本。全文涉及分公司的“净利润”均改为“考核利润”。委托者2018年12月下旬提出该项修订，但是三个月以来没有真正动笔。
- 5."增加条目“实股”根据分公司经理的考核得分对应解锁后，拥有公司一定数量的实股股份（注册股）。" --> 原版本已有几处用到“实股”，经核实委托人提出的“实股”并没有不同定义、并没有不同使用条款。
- 6. “增加条目“合伙企业股份”公司授予分公司经理的期股额度依照本制度约定的条件和程序解锁后，转为实股股权（注册股），并在合伙企业中列示。” --> 其他方提出持股平台注册为合伙企业，委托人以为合伙企业有股份，因此提出这项修订，并没有把持股平台注册为公司的明确构想。
-- “增加条目：纳思估值1亿元。估值依据。。。。。” -->  委托人没有想好要推、要反对的估值依据，只是会场上即兴发言。
-- “增加条目：1股价格。折算公式。。。。。” --> 同上。

### 16:14
大股东希望用期权方案兑现过去的奖励承诺，而且价格非常公道。分公司经理普遍认为自己贡献配得上赠送实股、而不是以个人现金购买。

委托人的思路：实际上无所作为，但自认为称职的做法是：
1. 撮合折算价，促进达成；
1. 简化方案：作为最后30分钟的工作。

### 16:44
借用hejie方案，分公司独立为子公司，经理购买子公司5%股份（按过去三年利润折算价），规定今后按考核利润分红。（结果被大股东干掉了）
借用昂立方案，分公司经理和校监投资新校区（\~30%），两三年盈利后公司按6\~8倍回购。（方案对未来扩张有激励作用，但是和过去的贡献承诺不完全同步）
没有其它自创内容。

分公司经理心中，目标责任书方案获得的现金已经可以满足，不再强求股份。  
大股东认为，虽然承诺过一起分享未来，但这份方案已经兑现，即使大家不购买也不需要再以其它方式兑现承诺。

**Comment by hyg** [comment]
## 3.27. 6:29
- 原本承诺以股权奖励过去贡献，后来不断增添新的条件，迟迟不能全部兑现；
- 企业需要融资扩张，否则几年后会遇到瓶颈；新投资方可能反对分红；
- 财务已经很规范，大股东也想分红，具体分红方案有待讨论。

**Comment by hyg** [comment]
## 3.27. 6:59
- 委托人过去一直负责运营，核心骨干都签订目标责任书，有提成激励，委托人只拿固定工资（？）；
- 去年开始出现利润，委托人希望按股份比例分红以外，单独有提成奖励；

因为亏损阶段的承诺没能整理出来，各股东以自己方式提现的情况也不明了，“分红”方案暂时不讨论。

**Comment by hyg** [comment]
## 3.27. 7:29
委托人和核心团队绑定的目标责任书关键条款：
核心要点还是卡住财务的收入计算及成本计算。这个模型不确定下来，后面的很难，都是一笔糊涂账。
1. 2020年初~融资成功前的目标责任书；平衡发展，销售额和利润关系比较固定。主要是控制集团总部开支，这个控制不住还是无法做出较高利润的。运营绩效中要把总部的成本进行剥离。这是一个重要的点。
1. 融资成功后同意分红的目标责任书；
1. 融资成功后对赌条件禁止分红的目标责任书；卡住对赌协议中的每年数据，提出运营绩效。

- 委托人在2009年与财务部讨论过报表内容和行列定义，没有彻底定制财务规则；
- 复习[根据业务定制的财务制度](https://github.com/xuemen/PSMD/issues/3)
- 委托人完成财务制度之前，以财务和运营数据继续脱节设计方案。只使用没有偏差的数据：
    - 收入
    - 工资

**Comment by hyg** [comment]
## 3.28.

1. 测算各方对企业的借款，协商达成一致。（参考 #2）
1. 参照其他员工目标责任书中的提成，提出过去贡献的估算方式（至2018或2019年末）。如果涉及财务统计数据的争议，应协商调整公式、改用无争议的数据。
1. 着手制定多套一体化的目标责任书，包括大小股东在内（2020年起）：
    1. 没有融资进入，目标责任书中包含融资谈判这项工作；
       - 营业额
       - 利润
       - 融资额和条件
       - 各人员提成方式
    1. 有融资进入，融资协议包含分红的约定；
       - 营业额
       - 利润
       - 分红和股份转让规则
       - 各人员期权及提成方式
    1. 有融资进入，融资协议包括不分红的约定；
       - 营业额
       - 利润
       - 股份转让规则
       - 各人员提成方式
    1. 一定条件下彻底退出，目标责任书中可以包含融资谈判这项工作；
       - 营业额
       - 利润
       - 融资额和条件
       - 各人员提成方式，包括委托者彻底退出的时间和方式
1. 一致行动人协议，核心是确立章程和股份不能用在内部，另遵守一套规则。
1. 制定和议事安排：...

**Comment by lidan1980** [comment]
1/承认协议自留地
2/最大化阶段性价值
3/准备：三种方案下最优化推演
4/形成文件
