### ISSUE TITLE
个人规划

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#81]
1. 整理自己在过去重大权利分配中的实际表现；
1. 提出未来各阶段的事业目标；
1. 明确当前所参与共同体在总体规划中的地位；
1. 在20~24点征求家人意见；
1. 提出半年内的关键工作，预测反对方、反对意见，制定应对措施。

**Comment by lidan1980** [comment]
预算体系驱动运营效率的提升。
1/定岗定编，控制人员预算
2/运营模式，合理利润的测算
3/工资体系的测算
4/职能部门的预算反推
5/财务核算体系的明确

**Comment by lidan1980** [comment]
1/因为恐惧而选择退缩和躲避模式，不思考，被动接受。
2/两年内仰攻，两年后构建中心能力
3/积累经验
