### ISSUE TITLE
试错型共同体

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#85]
在没有全局参考案例，必须经历多次失败才能完成的创新过程：
1. 如何保证创新者获得权力和资源，如何识别滥竽充数、削弱故步自封的成员；
1. 如何保护未兑现的利益，使既得利益者支持创新。

在这个主题下完成可以使用的启动文件，预测部署者在这套制度下需要完成哪些后续工作。

**Comment by lidan1980** [comment]
转变激励方式
1、根据财务指标，把分公司和校区分成三个等级，每个等级匹配相应的固定薪酬待遇。考核指标根据公司等级差异，分成现金流，现金流加利润，口碑加产品结构加利润。
2、员工分成行政服务岗，业务岗，校区总监学管师咨询师变成行政服务岗，教师变成业务岗，岗位分级别，按照目标达成比例进行综合评价，给员工评级，对一个级别工资。
3、挑选试点校区，并匹配新型的管理结构及激励方案和培训方案及分公司直属管理的压力测试。
4、对于分公司经理采用固定工资+绩效+期权的方式进行奖励。降低现金支付的比例。
强化总部能力
1、决策能力提升。在总部成立议事委员会，董事会。按照董事会进行操作。两人可以按照提议记录的方式进行。或者做好分工。把分工协议书写出来。在什么范畴内做出决策并承担责任。
2、会议能力提升。会前准备，会中执行，会后总结复盘归档并监督落实的整套体系提出来。
3、总部建模的能力。财务模型，装修模型，产品模型，运营模型的标准化输出。
4、产品能力。成立产品中心。由核心教师专职担任。主要的工作是研发可以使用的教材教辅及封装。画出其组织架构核心职权及分配模型。并能够在未来一年内承受攻击。
5、在线化推动方案。在线化实现的阻力抗拒点明确。对应奖惩措施。
核心岗位的任期制
1、任期制打破的观念是做的好就继续留任，做的不好就调离的观念。
2、任期制要打破某公司是某人的观念。
3、从利益分配上，核心岗位要拿集团总体分成，级别公司给高，绩效工资给低，分步激励期权。
4、基础是财务透明。财务透明是要规范创始股东的利益问题。创始股东统一拿上市后的回报作为基础。
5、核心员工要认同公司的战略投资，对于失败要共同承担。如何让核心员工认同失败。最终的方式是创始股东在能力不足的情况下，启动职业经理人制度。

**Comment by lidan1980** [comment]
基础
1、明确个人角色，经理的角色应该承担的责任和拥有的权利。
2、明确所要修订的文件是基本管理制度还是具体规章。
3、应用工单管理制度。
4、形成文档管理流程
前提
1、企业实际控制人的未来发展规划及利益兑现方式
2、企业非实际控制人未来规划及利益兑现方式
3、寻找共同利益点
具体工作
1、设立标准化推行部门及保障其有效运行的机制
2、设立教学管理部门及保障其有效运行的机制
3、优化成本机构提升利润率的方案
4、扩大营收规模的方案
5、承认现实的前提下增加控制力的方案
