### ISSUE TITLE
试错型部署者 

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#86]
1. 部署者要在第一次召集团队成员时提出哪些要约（参与即承诺）；
1. 首版顶级权利分配规则中要嵌入哪些关键条款；
1. 部署者在首版规章框架下，要持续完成哪些工作；
1. 部署者个人要如何准备，才能承担以上工作。

**Comment by lidan1980** [comment]
毁掉信任的恰恰是自己用信任在选人任事，而不是能力与客观评价。在组织内部形成派别。制约了企业的发展。首要建构的能力是客观评价的能力。从这点出发书写一个可以执行的方案。

**Comment by lidan1980** [comment]
1、保证体能及脑力高效输出的方案；
2、构建服务个人的团队
3、能够提出有效方案的前提下至少在关键利益和权力上做2次谈判
4、降低在具体运营事务上投入时间的方案
5、运用线上沟通的时间
