### ISSUE TITLE
目标责任书 

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#92]
收集关键各方的意见，分析每一个角色的责权利。

制定目标责任书相关的完整制度：
1. 规定目标责任书的制定、生效、修订、撤销等工作；
    - 如果这些工作也会随内外变化而修订，一直上溯到最顶层的权利分配；
    - 如果公司法、公司章程与上述顶层权利分配不兼容，则制度不依赖公司法和公司章程，且明确两套权利体系的衔接关系。
1. 谈判、签署的计划和需要使用的素材。
1. 半年内实际使用的目标责任书。

**Comment by lidan1980** [comment]
新版的而目责任书：形成力出一孔的价值。大盘子和小盘子的问题。
业绩目标，利润目标，口碑目标，组织建设目标。价值观评价。一共五个维度。
设定发展规划3年。3年内和3年后。三年内是常规激励，3年后是是超额激励。
也可以半对半。
对于校区也是这样的规定。
对于退休制度。及退休工作安排的考虑。

**Comment by hyg** [comment]
回到原始的实际控制模式下制定2020目标责任书。

有待补充的相关材料：
- NS原有权利分配规则下，制定这份目标责任书的真实指令是什么（包括口头的、隐含的）。重点是目标责任书的制定、修订、终止、撤销.....等权力的规定。
- 老版本目标责任书的内容和使用中的问题。重点是和NS原有的劳动合同、规章制度的关系（补充、独立、替代...）。

除了目标责任书的内容以外，也把它使用中的后续预案整理出来，作为配套的方案。

## 2019.9.25. 7:45~8:44
因为资料不全，不能直接讨论目标责任书内容。以下是口头讨论后的分析。

在奖金制度不完善、以口头承诺为主的早期，目标责任书起到保护骨干利益的作用。
随着NS现金充裕，违约风险逐渐降低，这项使命已经终结。

现在NS主要需求是利用旺季现金充裕的条件，改变未来在行业内的生态位。
对骨干的政策也要服务于这个需求，而不应该局限于目标责任书的字面意思，沿着现有格式盲目强化。


![image](https://user-images.githubusercontent.com/1675665/65562208-10a79b00-df78-11e9-9108-8c093a192fe8.png)
以问题6（联合抵制新合同，要求明年再启用）为典型：
格式合同的修订，根据修订内容的性质可能属于董事会(涉及基本管理制度）或经理（涉及具体规章）。和目标责任书的上位制度有交叉，但属于不同职权。
目标责任书要根据重要变化修订，因为没有配套制度去定义修订权，所以一年内僵化的目标导致新合同被抵制。

这个问题的性质，是目标责任书配套制度不完善、落后于公司发展的需要。不去完善上位制度，而是从被修订地位的目标责任书（一份表单）去改进时徒劳的。
如果规章制定工作继续瘫痪，不仅格式合同的改进，NS为了抓住市场机遇而推行的许多举措就会流产。

**Comment by lidan1980** [comment]
过往案例：
1、发标后不认同，签订时用的群体压力。签约后纠结。
2、总体目标需要增长，前期压，降标，完成好刚刚完成的，为明年增长设定一个小基数。
3、更高一级的管理者也想参与。更高一级管理者提前沟通，达成协议。架空实际管理者。
4、针对个别目标的计算方式扯皮。
解决问题思路：
1、塑造共识。基于高度共识产生的标书。
2、捍卫制定权。基于明确的权力，尤其是制定及修改的权利不可撼动的基础上产生的标书。
3、利益保障。在产生分歧，或者制定的高了，低了，外部环境发生变化，执行人发生变化了，标书的效力如何保障。

**Comment by lidan1980** [comment]
划分四个区域，江苏，杭州，嘉绍，宁台温四个战区，每个战区一个负责人。1.保底标为去年总体完成的95%。在此基础上进行竞标，一个人可以兼任两个区域的负责人。综合评分高者获胜。现金流3分，利润3分，口碑2分，干部贡献2分。最后综合得分多者获胜。获得标书的人要抵押一些东西。并且在第一季度未完成就要开始接受处罚。
如果连续两个季度无法完成指标，则这个职位开放竞争，循环程序1.
当出现特殊（受约人身故，主动放弃）等情况，这个职位卡房竞争，循环程序1.
当出现竞争环境变化（政府政策明确规定，如三个月收费，盈利限制等，影响到四个考核要素至少一种时）竞争对手策略明显针对所在区域的校区（高薪挖人，超低价挖学生）等情况时，2受约人可以提出降标，降标之后再发标，循环程序1.
当出现大型利好（所在区域学生涌入，好学校搬迁，新考试政策颁布，竞争对手内乱），则需要重新制定标书。2公开利好消息，及增幅标书标的，循环程序1.
当汇总目标连续两个季度无法达成时，3经理职位开放竞争，以去年同期完成95%为标的，所有已签标书作废，以信任经理获得的标书额度重新分配目标，区域经理职位开放竞争，循环程序1和2。
竞标改成一个经营方案，方案包含经营计划和目标的分解。同一个职位有两个竞争者则执行程序1。至少有一个校长来签字。

**Comment by lidan1980** [comment]
4对于职能部门不作为或效率低，业务部门举证，评审，通过，处罚决定下达，职能部门执行，反之亦然。
同时犯错，或重大事件（窝案，失火，踩踏，群体事件，大规模退费等），更换发起者执行程序3

**Comment by lidan1980** [comment]
找到和老树根的衔接部分，以协议的方式获得总包利益和总包权力
在总包的前提下设置利益分包和权力分包
识别并绑定协助者（利用公开信息及直接验证的方式识别，用等价交换的原则绑定。如：合同法构建组织的能力）
