### ISSUE TITLE
自觉共同体 

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#93]
根据自己的能力（需以历史记录支持）、意愿（需签署文件发给相关各方），协助者（需对方签署文件），提出一套自觉共同体的部署方案。（其中部署方案、自觉生态位的定义见[PSMD README文件](https://github.com/xuemen/PSMD/blob/master/README.md)）

制定部署计划，提出其中重点、难点、疑点，并一一给出解决方案。

**Comment by lidan1980** [comment]
班级课程自觉共同体的实践：
成立小三会
每个教师都是班级课程的股东。给每个入职教师按照规则颁发虚拟受限股。
所有决策都依照公司法进行。
权力捍卫利益的事情不做。
对于每个人承担的事情进行价值评估。
修炼重构能力和资源能力。
最重要的是在现有体制内如何实现对这套实践的保护。

**Comment by lidan1980** [comment]
班级项目如果能够获得：1.自我迭代职能----重构能力；2.以未来的成本获取优秀人才和产品及招生能力----资源能力，3.组织合规合法运行-----自我保障能力。有两种路径以公司法路径，成立新公司运行。另一种是以合同法为依据运行。
发起人起草章程，大家在章程上签字。
章程的要点为：n组织为寄生单位，负责处理对外事务部分。对内所有事务以可以根据任务重构的组织形态出现。公开竞聘的方式获得调配资源的权力形式存在。

**Comment by lidan1980** [comment]
组织：1发起者发起项目，参与者对项目调研，并写出项目计划书及运营规划资源需求，公示，投票决定，承担项目指标。2每个参与者可以发起项目，做项目说明，如通过，则对发起项目给予奖励。循环程序1。
利益：课时确认即刻获取积分，积分对应现金。现金获取后置。获取积分等值货币参与到滚动投入中，获利或亏损，进行等值计算。协议控制，3个人明确在1或2的程序中突入资金。4个人不明确在单个项目上投入资金。如盈利则4收益大于3*N个项目总和。

财务：
托管--财务规章核心条款，总体财务托管。托管机构的雇佣方为积分持有者代表大会，越远越兑现的人表决权越大。
支出--1常规运营支出做预算制度，积分持有者代表大会通过。按照年度进行。2超出预算部分，一事一议，有持有者代表大会推出的审计委员通过后执行。3当2未通过，则由提出超额预算者自己融资解决。成功获得收益外的融资收益，并减少审计委员权力。失败自己承担损失。

**Comment by lidan1980** [comment]
所以具体的规章是：
1**项目部负责人公开竞聘。如果没有竞聘者，则由项目发起人指定。
2**项目部负责人提出年度项目总目标，项目发起人制作第一版项目部负责人认可的分配方案，综合提成3%。签字确认。
3收益兑现，基本工资每月发放。绩效工资分为两部分。一部分按照半年度发放，一部分在次年发放。次年发放的部分可以投入到组织运转。按照投资比例设置回报额度。有两种可能性，一种是放入一个项目中，一个是放到总盘子里来。收益会有差别。
4保障收益的方式，班课项目单独立账，账目公开。向工资后置者公开。年度预算批准。单独项目投入的项目预算批准，投总盘子的，总盘子的项目预算批准。人少于15人，则全体投票。多余15人，用代表大会的方式投票。财务寄生在集团内部。体量到达***万级别，托管成本占总成本2%以内的时候，采用托管的方式。保证没有人能够挪用这笔钱。
5发起者召集会议，对核算机制发标，参与者在规定时间内参加会议同时提交机制文档，大家投票选出核算机制。

**Comment by lidan1980** [comment]
清晰的自我定位，在提出问题或者发生行为的时候，其他人断了动摇袭扰的念头。
在发生具体行为之前的筹备过程，能够清晰预判不同角色的行为及行为背后的思维过程
对于预期结果达成的难点有清晰的认知
理清角色清单，分析过往行为，预判行为延续带来的困难，方案预防和控制
方案的抗击打能力以及自己的压制力，尤其是在自己不熟练的关键动作上，反复锤炼
