### ISSUE TITLE
部署者

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#94]
分析 #92 #93 主题中部署者的工作情景，结合过去各主题的讨论内容，制定一套适合自己的个人领域模型及部署方案。

以自然人身份与相关各方接洽，在集结解散前收集尽可能多的反馈，约定四季度内的会面和谈判。

分析谈判难点并一一制定对策。

**Comment by lidan1980** [comment]
在过去的四年中，由于自己的不作为，使自己与开宗立派的个人定位越来越远。在psmd项目中，需要更大的推动力。急需构建一个机制，监控自己完成最急迫的事情。在自己不作为的时候，也能按照清醒的时候的决定执行。如果在明天上午无法输出有用的条款，转向下一个层级学习。下个季度再重新冲击。

**Comment by hyg** [comment]
在“分析 #92 #93 主题中部署者的工作情景”时，提出放弃。
重新回到周一晚19:45~19:59的步骤，选择“最近一年、未来半年的部署方案；其中的重点、难点、疑点。”

**Comment by lidan1980** [comment]
停滞不前是因为幻想太多，锤炼自己消灭幻想的能力是现阶段的重要能力。清楚自己的上限，根据上限做选择。如果是开创者的的行为就继续努力，如果是跟随者的行为就在跟随者上继续努力。是这个阶段最需要的做的。

**Comment by lidan1980** [comment]
在自我约束的90天时间内，
对自己每天具体产生的行为的提升目标。
对于自觉共同体的构建目标，
目标降低3倍，行动增加5倍。
