### ISSUE TITLE
上位制度

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#96]
目标责任书的旧模式是：
1. 一人调研、起草，一人审议、拍板；
1. 两人通过后再逐一和骨干谈其中参数。
实践中，更高目标取决于跨部门协作的效率。这需要调整规章，因此”目标责任书“的内容正逐渐扩展。但制订过程还没有主动适应这个趋势，超纲内容没能以对题的规章发布，因此固化了旧业务模式、压抑了创新试错的积极性。

请设计一套合同，交由相关各方选定角色、一一签署：
1. 各角色的层次分明、比例合理、责权利平衡；
1. 各角色能独立估算不同贡献的收益，竞争规则简洁，产生争报高目标的实际行为；
1. 能进行跨部门的试错、创新；
1. 与原有权利体系并立，取长补短。

这次主要是实践检验知识积累，务必选择合理目标、摆脱浮想，在解散前实际签署生效。

**Comment by lidan1980** [comment]
问题：以后每年目标责任书设定之前，需要分公司经理和人力等部门一同设计或者参与讨论。包括校长的。目的是强化认同，形成良性竞争，共同促进组织快速健康成长。你认为从程序上应该怎么设定，或者从具体规章上怎么设定，或者从指标上怎么设定。
L1回答：概括来讲就是写的那个猎狗和野牛的事情就是让这个组织建设来讲。我觉得还是得和企业的使命愿景价值观结合在一起，否则的话，讲的这些东西会冲淡形成的价值观。我们每次讲到这个组织建设，他肯定是跟使命愿景价值观结合在一块儿的，每个人都清楚企业应该机动性更强，组织结构更小，能够产生的效益更大，但是他跟这个价值观愿景结合在一块之后如何来实现？要永远讲成一套理念，否则的话可能今天会讲猎狗和犀牛，明天可能会讲什么蚂蚁型组织，海星型，那就导致我们在让那些文化有传承和落地的时候失去了灵魂和中心。很难沉淀下来。工作坊是有，物理场的也有心理场，通过描述愿景，然后分拆成战略，导出具体的目标，这样的话，我们所有目标责任书的签订不是公司的要求，变成了是基于实现一个伟大的教育梦想，而转化成的使命。这就相当于有了目标。有了目标之后，在工作坊当中我们再提供具体的方法去帮助大家得到如何实现目标的方法，最后再给到大家相应的激励方案，也就是说给足大家动力。那这个目标责任书的签订就变成了一个个人能力的提升。和心灵的净化。是在为一个伟大的教育梦想而奋斗，而不是在分钱分目标都转化成了压力啊。这样容易形成公司和分公司经理的对抗的局面，大家互相不理解，导致的结果永远就是藩镇割据，互相拆台。具体的机制设计，我觉得还是偏向于这种三权分立的结构啊，就是有评审委员会还有协调委员会和资源委员会。暂定这三个名字。使大家提上来的目标和需求，肯定需要一定的资源来满足，那协调委员会就是来调整分公司经理和总部的关系，那评审委员会就是来评估最终的目标责任书是否合情合理。评审委员会和资源委员会可以合并。然后把它当成一种机制给传承下来，执行委员会就是具体的分公司经理，所以分公司经理他要跟他主要的分公司负责人共同组成这个委员会，来最后执行这个方案。协调委员会可以负责处理分歧。发言权由评审委员会来决定。如果缺乏这样的机制和相应的组织，比如说这样的委员会，很容易让分公司经理跟总经理形成对立面。这样就导致把一个组织行为变成了倾向于是总经理的一个个人行为。我们要把它做成一个组织行为，而不是一个有太多个人印记的这种行为。然后最后稳定的组织结构，他也是分不同的层级的，首先在上面得建立一个稳定的小联盟关系，就是类似于决策委员会，其次中层主管成为一个中联盟关系。再下面涉及到基层员工和核心骨干，形成一个大联盟关系。
W2：W2：每年目标设定的不认同感主要来源于目前的资源形成目前的业绩，看不到未来的资源空间，也就看不到业绩目标增长的空间而形成焦虑抵抗情绪。
如果我们能组成一个熟悉分公司业务的指导团队每年做一次大梳理复盘。梳理出分公司的资源空间（人力潜能、市场潜能、业务模型、大事件增长点、业务节点得失、运营健康度、财务指标等），做一次全面体检，找到运营的资源空间，从各个纬度形成发展重点指导意见。或开新校或调整老校或调整人员配置或强化某块职能等等。
梳理出了资源空间，也找到掣肘发展的因子，着重调整或加强这几项因素来释放业绩空间。集团也可以精准扶贫。协同达到资源空间的释放。业绩的增长点也找出来了。目标就容易达成，也容易接受。
校区的目标也是同样模型操作。根据要调整方向设定额外绩效以促成目标达成。这样集团的人财行赋能可以体现出来且精准，站在第三方或许比当局者更清醒。一旦资源释放空间或者是业务方向找到了，指标也就因地制宜。不再是你多我少的矛盾了。

**Comment by lidan1980** [comment]
L2 回答：
制订校区总监绩效考核基于四点，l）销售业绩占比50%，2）课时消耗40%3）团队建设5% 4）满意度5%校长绩效根据地方经济，工资总额占校区课时收入x%为基准，低则优秀，高则找问题，高于y%涚明校长价值不大，可以调整；校区定校区需要完成多少业绩，课时才能保本作为底线，按你创造价值拿绩效；基本以总部2017年校监目标责任书为蓝本，上下浮动指标数。让校区目标更清晰，对如连续三个月不达标的校区，公司有权调整，调岗。

**Comment by lidan1980** [comment]
L3回答：
1：要有强大的仪式感，让分公司经理，校长乃至校区的所有老师知道，这个是校区明年的核心目标

2：目标责任书分开，现金流，课收，利润分成3个责任书，这样重视程度会提高，越细化越正规，越重视
 
3：目标要有追踪系统，每个月集团追踪和提醒分公司精力和校长你的目标完成的进度，并做提醒和鼓励
 
4：阶段性表扬，完成好的校区集团统一表彰营造氛围及安排分享，不仅仅限定为好校区，把困难校区做好了也要分享，做的好的有自信和荣誉，做的不好的可以做针对性学习。
 
3：把现有的校区分为4类校区：
 
A：新校区：关注人头和现金流
B：困难校区：关注现金流止损或者少损
C：一般校区：关注现金流和课收及利润的增长
D：好校区：关注现金流，课收的稳定和利润的增长
 
ABCD四类校区根据过往的，实收，课收，利润分析做第二年的目标，让接手的校长清楚明白你的指标很客观，只要你全力以赴就可以完成，同时有对应的激励。
 
分公司经理和校长是目标第一责任人，不要让他们感觉目标太容易或者太难
保底的用心就可以完成，冲刺的要努力全力以赴

**Comment by lidan1980** [comment]
C1回答：
1、目标责任书划分两档，增加了课耗的要求，希望在校长完成保底指标有绩效奖金的规划
2、对于校区目标的拆解，可以基于我们的业务关键KPI倒推来完成，但是苦于我们系统数据不准确，没有办法进行，系统数据不准，基层管理者就会对数据失去信任，失去了信任，就没有敬畏，导致我们的战略工作指导就失去了立足点，也失去了公信力，即使做的在科学，也不是相信在目标下发之时，而是在完成之后！

**Comment by lidan1980** [comment]
> C1回答：
> 1、目标责任书划分两档，增加了课耗的要求，希望在校长完成保底指标有绩效奖金的规划
> 2、对于校区目标的拆解，可以基于我们的业务关键KPI倒推来完成，但是苦于我们系统数据不准确，没有办法进行，系统数据不准，基层管理者就会对数据失去信任，失去了信任，就没有敬畏，导致我们的战略工作指导就失去了立足点，也失去了公信力，即使做的在科学，也不是相信在目标下发之时，而是在完成之后！

[建议.docx](https://github.com/xuemen/PSMD/files/3971114/default.docx)

**Comment by lidan1980** [comment]
L3回复
三份正式一点的文件，包装精美，只有目标明细，没有奖励，奖励单独发给对应的校长。
实收的业务团队派代表和校长一起签署
课收的学管，教学代表和校长一起签署
利润校区所有部门代表和校长一起签署
让所有人都参与进来，不仅仅是校长的目标，是这个校区所有人的目标

**Comment by lidan1980** [comment]
L1
[目标责任书修订建议(1).pdf](https://github.com/xuemen/PSMD/files/3975761/1.pdf)
18日晚上22.29

**Comment by lidan1980** [comment]
S1回复
S1
有没有一种办法，是让员工尤其是牛逼的员工发自内心的希望把这件事情推到自己和团队的能力极限？
我想了很久，很难用单一要素去实现这一点，需要综合各方面，首先，要获得员工理念和价值层面的认同，这一点可以通过沟通实现；其次，物质激励也要合理，跳跳够得着，最好要有同比竞争力，但不是最重要；然后，设定目标，积极反馈，做对事及时奖励，做错事时候用宽慰拉近距离；最后，把个人的业绩绑定个人晋升和团队的荣誉。

合作协议中有哪些问题，这些问题导致了怎样的后果。这些后果对员工的工作产生了阻碍。如果让你重新制定这份协议，你要怎么修改？
目前合作协议，整体感觉是有些霸王条款，而且合作价格以及消耗费用不明确不明示，
合作年限要求一年内消耗完，这些都缺乏用户思维，包括后面配套的运营服务专员个别职业精神和业务素养不太理想。
以上这些对员工影响都是在可控范围，本身这个项目单底也不大，所以即便遇到比较较真儿的客户，也不会因为协议里哪个条款拒绝合作。但是，给员工留下了公司不够人性化缺乏公正的印象，这一点是不好的。
但是，上面这些都是我无法改变的，如果让我重新制定这份协议，我会清楚标注合作费用以及消耗标准等，把首充消耗年限扩大到两年。
但是，我却想不明白这个问题是什么意思。

如果有人向你介绍一个新的项目，或者你要向别人推一个新的项目，没有加持，别人还愿意去做，不仅仅是尝试，而是发自内心的原意并会投入自己最好的资源与你合作，-------怎么样做才能达到这样的效果。结合你的实践，想几条出来。
（客户视角--从客户的角度分析事情，没有品牌借力，依然愿意全力以赴，怎么才能使然）
1、如果没有品牌的加持，客户依然跟我合作，那就需要一个前提，就是客户对我必须高度的认可和信任，这个不是一两日之工，需要多次接触才能构建信任，这就需要销售具备成就客户的信念和理想。
2、还需要一个前提是我本身要对自己出售的产品，从功能上高度认可，我卖不出来自己不认可的东西，这需要在理念层面给销售洗脑，让他产生对这个事情的高度认同。
3、还需要一点，就是得让客户感觉到他在我这里购买产品可以获得比从大品牌购买一个产品有更大的收益，这个需要用服务来取胜，需要用个人魅力去增加砝码，这个需要销售从必须超级熟悉客户业务和场景。

**Comment by lidan1980** [comment]
目标产生方案
1、目标：现金收入额（元）、确认收入额（元）利润额（元）其他相关指标（例如开拓效率等相关指标）
2、目标产生：
   固定产生法---固定增长率设定下一年度的基本指标
   行业对标法---根据行业上市公司头部企业的增幅设定
   提案法----董事会提案，董事长提案，独立董提案，
股东会批准，利益方回避，制定者和执行者分开
3、竞标：
   指标产生对外发布，在20个工作日内接受竞标方案。
   对外发布奖罚原则-----超额激励，达成收益，未达成处罚
   竞标者提出预算案和运营方案，
接受提案者于10个工作日内确定竞标胜出者
4、签订协议。
5、指标难产
12月1日前无法确定指标，则以连续24个月产生指标的平均值自动产生指标。
6、无人竞标
  股东会重选董事会，重复1-4
股东会选出一名股东执行，按照上一年度目标的50%制定，
无股东愿意执行，公司托管运营，出售
无法出售则解散
