### ISSUE TITLE
未来收益合约

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#97]
以未来收益换取现在资源时，资源募集者或资源持有者向你征求意见。请为此准备一套合同，消除常见的违约行为，降低合作风险。根据实际需要可以作为合约中的持续参与者。

尽快完成起草，把更多时间用来讨论反馈意见，争取在解散前进入实际使用。

**Comment by lidan1980** [comment]
投资方需控制的条款

1、对于股东兼任其他职务的约定：如股东兼任其他职务，均需开放竞聘，同工同酬，竞聘决定权与股东权力重叠的，股东回避。
2、对于利润分红相关条款的约定：经营性支出审批，报销管理规范，薪酬设定，关联交易审查。防止挪用及超额开支。经营者应与员工报销额度一致。超额部分自己承担。
3、对于过渡型股权设计的约定：先借债，达成目标后约定债转股。
4、关于公司章程中议事方式及表决程序的约定：涉及投资利益的条款，通过表决权应不低于所持股权加被投资人股权数量之和的标准。
5、如以合伙企业投资，则召集人制定合伙企业章程，审定此章程。
6、以上条款写入章程，根据自己投资比例，设定表决通过的比例。防止改来改去。

融资方需控制的条款
1、对于投资方要了权力但不行使权力，以致影响正常经营的，视为自动放弃此项权力。多数通过也可以生效。

**Comment by lidan1980** [comment]
目标产生方案
1、目标：现金收入额（元）、确认收入额（元）利润额（元）其他相关指标（例如开拓效率等相关指标）
2、目标产生：
   固定产生法---固定增长率设定下一年度的基本指标
   行业对标法---根据行业上市公司头部企业的增幅设定
   提案法----董事会提案，董事长提案，独立董提案，
股东会批准，利益方回避，制定者和执行者分开
3、竞标：
   指标产生对外发布，在20个工作日内接受竞标方案。
   对外发布奖罚原则-----超额激励，达成收益，未达成处罚
   竞标者提出预算案和运营方案，
接受提案者于10个工作日内确定竞标胜出者
4、签订协议。
5、指标难产
12月1日前无法确定指标，则以连续24个月产生指标的平均值自动产生指标。
6、无人竞标
  股东会重选董事会，重复1-4
股东会选出一名股东执行，按照上一年度目标的50%制定，
无股东愿意执行，公司托管运营，出售
无法出售则解散

**Comment by lidan1980** [comment]
1.价值评估：要重构一个企业第一个面临的问题就是评估评价。基于历史贡献，投入资金，在同工同酬，金钱的价值对等的情况下评估能力。所人有都希望把自己的功劳说的大大的，把自己的利益要的高高的。为了平衡这个，必须要谈，反复谈。并且有准备的谈。谈之前要获得信息，并且进行调研，还要签订框架协议-----就是必须出结果，如果出不来结果，扔硬币也要出一个结果。
2.识别违约。绑定连带责任高效的阻击浑水摸鱼的人和洗刷弱者，有层次，对攻推演之后可以选择和平，博弈的最高境界，使得权力重新分配过程中尽量减少抵抗；新人进来后能够得到很好的保障，包括对过往数据的公开透明。对以后收益的保障条款；资本趋向于能够有创新能力，发展能力，重构能力的组织，这样的组织发展速度会更快。
3.朴新三倍工资挖人可能不是其成功的关键要素，重要的是他建立了一套识别人的机制，如何让这些人下30-40天内交出工作结果，不能交出结果的就走人。识别这些人的机制才是他们成功的重点。另外朴新建立非常牛逼的标准化操作体系。使得他们能够快速的整合行业中的三线四线机构。高速是在任何环节上都高速和高效。相比较来讲，现有的重构能力水平太差了。对于每件事情都拖拉，不做决定，也不做选择。另外，如果这些识别人的方法和能力只在沙的脑袋里，就不算关键能力。如果能够写在制度里。如果能够让这些人彼此验证彼此消磨，同时管控这些人的接口是一个公用接口，一个小姑娘通过收集真实信息，三五个人同时杀到面前，部署者都可以有充分的准备时间，充分的沟通时间和有效的压制他们。
