### ISSUE TITLE
协从和披露

### ISSUE THREAD

**Issue by hyg** [xuemen/PSMD#98]
1. 观察其它主题工作过程，选定自己的职责，设计个人领域的协从角色；
1. 检讨个人定位滑坡的原因，设计对策；
1. 提出持续的信息披露规则、对应的罚则，降低协从角色的风险；
1. 起草协从角色的合同，进入实际谈判和签署。

**Comment by lidan1980** [comment]
S1 回复
有没有一种办法，是让员工尤其是牛逼的员工发自内心的希望把这件事情推到自己和团队的能力极限？
我想了很久，很难用单一要素去实现这一点，需要综合各方面，首先，要获得员工理念和价值层面的认同，这一点可以通过沟通实现；其次，物质激励也要合理，跳跳够得着，最好要有同比竞争力，但不是最重要；然后，设定目标，积极反馈，做对事及时奖励，做错事时候用宽慰拉近距离；最后，把个人的业绩绑定个人晋升和团队的荣誉。

合作协议中有哪些问题，这些问题导致了怎样的后果。这些后果对员工的工作产生了阻碍。如果让你重新制定这份协议，你要怎么修改？
目前合作协议，整体感觉是有些霸王条款，而且合作价格以及消耗费用不明确不明示，
合作年限要求一年内消耗完，这些都缺乏用户思维，包括后面配套的运营服务专员个别职业精神和业务素养不太理想。
以上这些对员工影响都是在可控范围，本身这个项目单底也不大，所以即便遇到比较较真儿的客户，也不会因为协议里哪个条款拒绝合作。但是，给员工留下了公司不够人性化缺乏公正的印象，这一点是不好的。
但是，上面这些都是我无法改变的，如果让我重新制定这份协议，我会清楚标注合作费用以及消耗标准等，把首充消耗年限扩大到两年。
但是，我却想不明白这个问题是什么意思。

如果有人向你介绍一个新的项目，或者你要向别人推一个新的项目，没有加持，别人还愿意去做，不仅仅是尝试，而是发自内心的原意并会投入自己最好的资源与你合作，-------怎么样做才能达到这样的效果。结合你的实践，想几条出来。
（客户视角--从客户的角度分析事情，没有品牌借力，依然愿意全力以赴，怎么才能使然）
1、如果没有品牌的加持，客户依然跟我合作，那就需要一个前提，就是客户对我必须高度的认可和信任，这个不是一两日之工，需要多次接触才能构建信任，这就需要销售具备成就客户的信念和理想。
2、还需要一个前提是我本身要对自己出售的产品，从功能上高度认可，我卖不出来自己不认可的东西，这需要在理念层面给销售洗脑，让他产生对这个事情的高度认同。
3、还需要一点，就是得让客户感觉到他在我这里购买产品可以获得比从大品牌购买一个产品有更大的收益，这个需要用服务来取胜，需要用个人魅力去增加砝码，这个需要销售从必须超级熟悉客户业务和场景。

**Comment by lidan1980** [comment]
协从角色设计：
甲方：委托人
乙方：受托人

目的：促进委托人完成核心架构搭建，产生具有法律效力的文件，走出原始陷阱，提升重构能力和资源能力，贼公平公正诚信的基础上，与受托人协商一致，订立合同如下：
一、乙方担任甲方的法律顾问、财务顾问、项目顾问、执行督查。。。。（可以选一个角色），在角色要求的范畴内为甲方提供服务，甲方支付乙方合理报酬。
二、乙方所担任所有职务、职责及所获得报酬，均是公开信息，其它人员也可以公开来竞聘。
三、乙方服务期间产生的费用由一个分摊规则。
四、乙方收益核算为一个固定值。按照时间进行费用计算。每分钟为60元。提前充值。每周固定时间为30分钟。
五、甲方将一次缴清3个月的费用及一个月的押金。在第二个月时提出下个月是否继续合作的邀约。如果没有提出则是续费。如未按时缴费，则扣除一个月押金。
保密约定。甲方发出的文件默认为可以公开的文件。

**Comment by lidan1980** [comment]
目的：促进乙方养成良好的工作记录的习惯，在公平公正诚信的基础上，与受托人协商一致，订立合同如下：
七、乙方担任甲方的法律顾问、财务顾问、项目顾问、执行督查。。。。（可以选一个角色），在角色要求的范畴内为甲方提供服务，甲方支付乙方合理报酬。
八、乙方所担任所有职务、职责及所获得报酬，均是公开信息，其它人员也可以公开来竞聘。
九、乙方服务期间产生的费用由一个分摊规则。
十、乙方收益核算为一个固定值。按照时间进行费用计算。每分钟为15元。提前充值。每周固定时间为30分钟。
十一、甲方将一次缴清3个月的费用及一个月的押金。在第二个月时提出下个月是否继续合作的邀约。如果没有提出则是续费。如未按时缴费，则扣除一个月押金。
十二、保密约定。甲方发出的文件默认为可以公开的文件。

形成的结果是未来三十天有每周一份工作记录
